// pinyindlg.h : interface of the CPinyinDlg class
//
/////////////////////////////////////////////////////////////////////////////

#pragma once

static const CStringW g_TxtToPy[] =        
{
	L"A°¢°¡ï¹àÄ…°¥°§°¦°£°¤œâïÍæX†Þß°¨ƒùœÜ‡B”²°}°©š±•làÈ°«°ªÜt‡†Ì@×cö°ì\°¬´°®íÁ³v°¯àÉ‰aæÈÛ°­êÓè¨ƒv‰¹‹Ü‘°ËB•á­aø°Š²}ñLèP÷o°²ó^èñ°±âÖÚÏÈsÄWðÆÉŽÕYì”°°±QñKõc±Ví†±ëˆˆ"   ,
	L"A°³††Ûûï§ë@ÞîÁOä@áí°¶°´ÇI°¸°·ØtˆÝ‹F°µØƒ‡åB÷ö°¹Œì°º•n–‹°»ál°¼Ûêˆ–ÀÝE n°½…ëJà»†õåâÚEéáª‡åÛ°¾­HÊT°¿ñúòüÂKÖ’ÂO÷¡÷éö—úqüÆb°ÀæÁéOÒ\á®’UC°ÁŠS°Â‹®‘RæñŠWŽS°Ä°Ã“ýÖ“öË"   ,
	L"B°Ë”°Í°È°Ç–[«X°ÉŠBá±°Å°Ì†^°Æ°ÊôÎ¼“ÁjÍMášØ^÷„ôƒ…© ã’iˆzŠ‚°ÎÜØžß°jÃ_á—ÝÃÔy°ÏÝR÷É°Ñ°Ð°Óy°Öˆ¢°ÕöÑõEÒ†³F°Ô‰Îå±™ñ’“êþ°×°Ù°Û°Ø–àÞã¸q»“°Ú”[ÒoßÂ’…°Ü°Ý†h”¡°Þ»Ÿì‹ËbÙ”ƒÄ®B°â"   ,
	L"B”‘°à°ã°ä°ß°á”Êñ£Î†ñ­ÞnÚæÛàŒê•L°å°æ­šîÓ»{ô²âkÎZô‘°ì°ë°é°çŠ”E°è°í¶t½Oã[ì‡Þk°ê°îLˆ °ï’Ê°ðäºß™Ž°ŽÀ¿RŽÍíD°ó½‰°ñ°ò«g°ö°ø°ô°ù‰Y¶œÝòÎM°õ°÷ÅÖrÙè°üÜæß°ú°û¸ìÒöµÊ}°ýé–ý_"   ,
	L"B·‘‹›±¢±¦A±¥±£ð±«’±¤ˆç‹~ÝáŒ‡ï’ï–ñÙñhøR¾‹ødÙ…ËŒ—Œšìd„ô±¨±§±ªõÀÇ˜±«ìsób±©óŽÌ™ƒ˜•Þ±¬ÞètÈ`Úé±°±­° —G±¯“d±®ðÇËùl†Õ±±ãm±´±·ØÚý±¸•K ´Æp±³±µ‚p±¶ã£ªN±»‚³‚Ë—f¬Dàf‚äƒF±¹"   ,
	L"B±ºÝK±²ÊíÕ¶FÝíÍ“ ÍñØÕRócÝ…ä^‘v¼L÷¹öÍ±¼›yêÚ‚–œ`ßG Äï¼åQ±¾±½ŠMÛÎ—ñÛÐ’Ù—L±¿“àÝ™È±À±ÁéaÐàÔ¾X¿‡±ÂˆÈÈE¬eìž±Ã±Å‰lê´éG±Äça*šÈ±ÆØP÷”ùSös–ÄÝ©±Ç‹ïØ°±È‰ý–aÓßÁåþ›a¯H±Ë–©ïõ"   ,
	L"BÙÂ±Ê»ô°¹P±ÉÂØ„„ö±Ò±Ø±Ï±ÕØˆf±Ó×ß›ŠŒPî¯®nßÙ±Ñ«¯RÜê±Ý±Ðáù®…Ð‹îéæ¾âØ±Ö—aÝÉÈ]é[é]ˆãŒåöÏã¹œ °zµ–óÙÔvÙCÚP†ô’—éääœüŸ•±ÔÄb±ÍÉœÍšñÔõÏésïŽÅ±×ŸÎªŒ±Ìóë¾a±ÎàŠñEŽÆ§ª‹"   ,
	L"BÁXÒKñƒó±ÚæÔYó÷º`¿oÞµÓv±ÜõI”Àå¨±ÛÛ‹÷ÂŠ`èµàˆð{ÀVôÅÒgç@íSí{ÜKÜLôxÚFèEòúzú‡ü„±ßí¾óÖ±àìÔ®K¹¾Žòùª ß„æQöýß…±Þöböc»ež×±á±âñ¹ØÒÆíÜ·HñÛ¼DøuËx±åÛÍâí’\›MãêÜÐáŠO±ã±ä‰ä•c"   ,
	L"BÒŒ“OçÂ±éÞgÅŒÞl±æ±ç±èÞp×ƒ±ë±êì©÷ÔªYÃ ‰wŽ¼œýæô˜ËŸÏ±ìñ¦ïÚì­ì®ƒšï[žd gÅAÙ™çSïðïjïkïlïnès±íæ»ñÑÕ•ÒFål™~‚l÷§÷B±ï±î÷Mü‚Ì‹ý–„e±ð…ñÇaÍrÖÒXÏhõ¿±ñ°T•ß“±ö±òÙÏ±ó—Ã±õçÍéÄ¬žÙe"   ,
	L"BÙfïÙƒ†±ôžIžMÌžáÙžlìEÀ_Ï™è\î šà±÷éëë÷ó‰”Póš›Äœ÷Æ÷ÞóxôW•šê±ù±ø–Þ’ò—€ä‰™‰±ûÚûêvT’m±üÆu•m±ú±þ±ý·’Ís—ŠÙ÷âìïžðV ]²¢KãŽÕˆ—Žð‚v–â²¡¸p‚§‚ìŒ}ÞðÕ@õmìh°h²¦²¨²£°þ±CÑB²§"   ,
	L"BâÄà£¼žÀ²±²¤ã\ƒ`ó²¥ðGÜ@ò’÷Q²®ØÃ²µ²¯²´ þ­“‚N²ªÃ`àRÙñ’©›Â¶zîà²¬²°²©²³È•ð¾ö²«â“ãKñA÷ˆƒkŸ¹ ¦²­²²Å‡ñCñgõÛäcéD±¡ñ•õN‘ÅµRº~ænðoùP Ý™ØÒqíçè}õË¹ô¤ŒXë¢éÞ¼\×LÌYÊNmŽïåÍ"   ,
	L"BîßêÎâ˜ÕcðJÞKõ³²·ß²²¹²¸²¶ÑaøGûQ²»²¼Ñ²½…ù²ÀšhšiîÐ„Ïˆ¶‹²¿²ºê³EÉžÛYº^ðX²¾çã·ðº»å²ðÚÆÙ"   ,
	L"Càê²Áíåµgßn²Â²Å²Ä²ÆØ”‘å²Ã²É‚šˆÆŠéŒu²Ê’ñ²ÇÛP¾Z²È²Ë—²Ì¿nk²Îï{æîœ’‹Û²Íò‰²Ð²Ï²Ñšˆ‘MÎ]‘LÐQÐT²Ò‘K‡k‘”÷õüo²ÓôÓƒ…ÓËL Nè² |²Ö¨Ø÷²×²Ô‚}²Õ‚áƒûÈœæªÉnžPÅ“Ï@À˜²Ø™âè†Ù‰“Ù²Ù"   ,
	L"C²Ú•ù²ÜàÐæäîÉ˜²ÛÒGô½ó©ç[Ü³ÆH²Ýóòx*Ò_²á²à²Þâü²âÇR”˜ÈYÅœy²ßÈm¹ZÉƒ‰x¹‹‘ŠßÄ~á¯—qä¹àá²ãŒÓ¸}òš²ä³€³’Kªeu²æÆOè¾ÃPÅaÓ‚²†â²åâÇã˜ïÊÅ‘®›åšðlˆ“²é–Ë²ç²è¿²ëâªìxé¶²ì²êéß"   ,
	L"CñÃïïèdŠgãâ²í÷²ïæ±²î¼p²ðîÎâO åÙ­²ñµ}²ò†¶ƒŠò²ÐƒðûÏŠ‡ÐÞ{êè—{²ô²óäiŽÊæ¿²÷åî—œµìø²ö‹ÈŸž²øª†²õÕSäaâÜ¨äý¿C´vš´àšïâžeƒ§„­ó¸àž‡Á‰ÊŽfžÀpÀsõðéKÆB×‹èð’²ú„i•CP›º„}ÚÆ®a®b"   ,
	L"C²ù²ûÝÛ„•ÝIŽÂÊrÕ~éˆºoÙæÀAápçPêU‡Ïž¬×€âã³ƒ“·‘Ï²ü‘Ôåñí]Øö²ýæ½œC²þÝÅãÑ•˜—Ç¬dÑmè å_öðöKüƒ¸³¦ÜÉ³¢³¥³£áä®DÈO®^Äc‡LæÏ¬ Äqä–ƒ”‡ŸÏ^÷•çL÷l³§³¡êÆã®³¨ƒY…”Së©äâê«`³©³«ÛË³ª"   ,
	L"C•³®˜Õkío³­€â÷™ù³®ìÌ³¬ân¿ž ŸêË³²Žz³¯à}R³°³±¸JÁVÞC³³³´±|Ÿ·ûžŽlžñéÓe³µÜ‡íº†qÇp³ŒÍ’³¶‚®“Ýåø³¹ÛåÞŠŸEÂs³¸³îJØ³·³º„ï²u …ÞÓ³»—²è¡àÁÕ€Ùo³¾³¼³À³Á³½³ÂÆå·ŸGÇk”³¿ÔHÚÈ"   ,
	L"C“ZŸ‹Êc‰m˜¹¯„ëÏIÖRËlû‰•æúmÚ’³•í×‰}‰ö´~Û{Ù•´³³Ä¯M³Æö³³Ãé´·QýYýZ‡¸ÚßÒr×êp›„èß —¢›Õ‚ òÉîõ ª¬bÚW‘r“£ìl“Î³Å¿B˜ûîªÚXîd™f¸V·Ï|çdçpð‰Ø©³É³Ê³ÐèÇ³ÏàJ³ÇŒkw›“Ç^³ËÛô’¬¬A’Þ"   ,
	L"C·œÃ”îñˆá³Í—–—¼³Ì¹f½†ñÎëó‰SœË³Õ\®—õ¨ä…¯³Î³È™rõ“žj‘Íòr‘³Ñ³ÒŽñ±òG³Ó³ÔŠw–oøßê«ò¿ð·®Eí÷ó×ÔWàÍæÊ“¤³Õ²ló¤ø|ùA°V÷Îýc”~üJ¯ü[³Ú³Ø³Û³ÙIÜÝ³Ö¸‡ÇKœF¹MÙPßWñYÜ¯õØóøÖs³ß…µ"   ,
	L"C…ÕÃL³Þ…q³Ýˆ‰Ãnu³ÜÍNôùšIšnÑlãrñÝýXáÜß³³âžÃ³àâÁ’x„Èp³ãÁ‹³áë·ŸU¯bà´œ‰ÙÑ¯vÄSãMë†‘yÂ@ßo‘Jñ¡ÂBŸë‘´Ú†ð„ùúu³ä³åâç›_Üû›Ò«–Áˆô©†ü“›‘oã¿ÐnÁZô¾ÛŒ³æ³çƒê™³èï¥ã|³éñ¬ºN ß â³ð"   ,
	L"CÙ±àü–äã°³ñÇ“³ë½[³î°{³í³ïáO³ê³ìël‹á‘À böÅ® ÜP×‡×‰³óE…Á–„‚G³òáh²ƒô{³ôßcšŽ³öŒç³õ“¹éËØŒýiÛ»³ý³ø³üÉZØa³ú˜ZÂaÉeòÜÚn³û ËNºX³÷‘ÃŽÐ™ŸÏ{³ù™»õéúRÜXèÆ´¡—Æ´¢èúµ—³þñÒéƒ¦™s­l"   ,
	L"CµAýsýƒØ¡„I´¦¸aâð’}ç©ØX¸e¬G½I‚â¬`às´¤´¥ÛUézƒãÀ™[”ßšbÄ•÷íÓ|´£ÞõÄu´§à¨àÜõßçÝ´¨ë°´©„”¬´«ô­´¬‡ùå×´ªšN•ÄÝŽâ¶ÇF´­ƒbšö´®«[îËâAÙi„V´Ñ´¯·™´° ¡“œ §¯¸R´² —‡l‚ü´}êJ´´âë„k„y"   ,
	L"C„€í´µ´¶ý—´¹–ûÚï´·Ç”é¢é³´¸åNîq•I–~´ºÈN‰@‹a•«´»˜‡¬t¹—òí˜ê™šöjùœ´¿ê´½›ÌÝ»´¾Ã‹ Æœ÷ÉOðÈ_´¼ácõž‚¤ÈoÃ²QÙƒÛw´ÀõÖ´ÁÞuŠÆ·›í´ÂßOê¡áQ¾bÝzöº“ó´‡šf‡ÇýpèqßÚ«u´ÃÚe‚½´Ê«yˆˆ–²"   ,
	L"CìôÜë´Ä´ÉÔ~Þe´È®N´Ç´Å´ÆðËôÙÞiï“ð@‹ãžBøyµQÞoú\ú]´ËÕ°r–c´Îè´Ì„pŽãÆ˜–æÇ„½aÍy´ÍÎˆÙn†ï´Ó´Ò‡èÜÊòèÈÆ‰S•Ÿt´Ð^Â‡Ê[æõ•¾˜Ú­Bè®ÂŒ´Ï²jºbÂ”ÏZÀSçWò^ò‹´Ô¾ŠæŒQÀ›äÈçý‘FÕpÙz"   ,
	L"CÙ{˜âËq…²žš™ß Ö´Õœé¨ëíê£Ý´ÖÓcû€û‚û›áÞéã´Ùâ§‹{¯|ÝýÕKÚu‘–´×¯•´Ø¿qõ¾üyõíÜAî•Ùàß¥ïé´Ú”xÜfè‰”e™«Žm´ÜŸä´Ûš–ºx¸Zìà´Þ´ßƒþ‰…‘N´ÝéÁª‰´…çJtyè­°„õ¯QÁŒÃy´àßý†Ÿã²´ãÝÍë¥Ÿn"   ,
	L"C´á´â´äÄ‹Äƒ¸WÒPÄ›ß—´åñå´¸€´æ„Yââ´ç»v´ê¬›ßu´è´éõãáióqÌ‘áÏÕðîïóÉcõºûzý€ëâ„v„zØÈ‰è´ìÇsÇu´ëßH— ï±Éx´íäSØÖÉ²ÐóÔøëúå¤æöôÒ"   ,
	L"DÔŒÒbŸíÖŠbÍBˆkÍhÚdÛL“_Ñnƒ‰ŽÎº@“€åTÛq…¼…ößÕÞÇ®†´îàªñ×‡}‰¡´ïæ§âòˆ™žØÁeÇQ…AóÎ´ðÔzÛQ´ñ÷°ËR÷² [ÀJÏƒÜJèNý‘ý“´ò´ó‡±o™\´ôªy‘·´õ´ö´úšùÞaþˆ‚á·Ž‘ß°çªåÊ´ø´ýµ¡–±´ùçé´ûŽ¡ÜÜ¤"   ,
	L"DŽ§½H´ü´þÝD¬x…¦•Î¿Dõ\øl´÷Å•÷ìº‰žŽìOÒyì^µ¤Šlµ¥µ£íñ³NÂnµ¢µ¦ñõÜl‹[ééð÷…SóìÑàîFÙÙ„éš—ÒRº„Â›„[ ý«m­µ¨Ðyðã¼µ§ñdÚü^Ä‘µ©µ«Ž›X›µ®–½¯Dà¢†›µ¯µ¬µ­ÝÌµ°†²µªÄEÍžÓg·žÕQ‡nó‡"   ,
	L"D‘„‘žå£¶Vñšø}®X°Q‡·ÙœìKð…µ±«šñÉ¹Y®”ƒ}‡ŽÇ­cÒdºšÅ™Ï}µ²µ³ÚÔ“õ×[žª×•šëÛÊˆWå´í¸ˆ›µ´µµÝÐ®Gë‹´X²^Ú‰³™n­T±UµDµ¶ß¶Œàâáë®Åsá’÷ô€’Òµ¼µºê‰µ¹uµ·µ»µ”“vëIëì˜˜Œ§ëZ‰»ŽW”Fµ¸¶\"   ,
	L"Dµ½µ¿µÁÈK—Í±IµÀ·R‡‹µ¾Ðm™|ÐpÂRÜ„­ôîzµÃ›úœ¿ï½‡NÔµÂåuµÄ“g’O’YµÆµÇØOàâ‹¿Ÿô­O¸~ô£Å˜ÓRµÅµÈê­µËµÊà‡ëQ‰œáØµÉíãïë™žç‹ªµÍµÐ”†¬ˆ¹ôÆêµÌÚhàÖµÎïá´”íLçCfµÒÃJÙáÆmµÏ†vµÐµÓ"   ,
	L"DÝ¶—bµÑêëì{œìµÕÊHÊLîEô†”³‡”Ë‹Øp¼eûMØµ…}Ú®Û¡ês…àÛæµ×~µÖèÜíÆ’ãÇœÝBÂ‚÷¾öWµØµÜ•A–m«ZK–š‚dµÛˆ¯æ·µÝÞž‚±—\Ÿb±ƒµµÚÇ…ÚÐâKé¦íûµÞµÙƒC¶EÄVãdñV‰„‰—íÚÊO‘d®S¾†ŽRÏEàÇ”“µà‚Ù…ŽÑ"   ,
	L"Dµá˜•¯’µßÛ†áÛñ²ŽoŽp”„°dý‚µäŠHµã‹L”¥—ÏµâÉ_ÊsõÚµçµèµéÚçÛãµêµæ‘úçèîäŠûµëµíµì¬UµîÍŸëŠ‰|‰«˜ëÕµå´ñ°ô¡ò›µóµðšô„aÍ@µòŠP‡¬Íq¬hõõµïš“²fµñõMöôºyü—õ ùmŒÅt®µõµö·–ÓŽµôážîö"   ,
	L"Dây¸uäHë¯š¸Lä”èSµùµøÒBÆ|µüÛìUgÀ„Ã]ð¬±yÂW‘äµýÜ¦Ž²Þé®’½xñóÔeµþšŠ šëºéPÞµúÎHÑÅŽµû®õÞöø•è¯A¯BšÛ‡Ã¶¡Øê¶£ŽŠçà®kðÛ¶¢¶¤ñôôúìw¶¥í”¶¦àËYç–¶©ð—³G¶¨Ó†ï}à¤Èb—ÅëëíÖ¶§´OÂˆ"   ,
	L"DåV´îrG¶ªîûïMäA¶«¶¬ßËá´–|Æ{•kë±‚”ð´ˆÄŠàž›ò¸•Ç‡šæÎXõ[üŠöCù…úH¶­‹Ù¶®¹šÊÕ‰¶¯¶³¶±ÛíŠŸá¼¶²’œ¶°¶´ëËÞ“ƒö‘ãëØ„Ó–íÏ—ÄLƒPñŽëš„r†t¶¼¶µƒÃÝú™XóûÅ¶·cêh¶¶¶¸ò½â^¶¹àK›ÃÇW¶º"   ,
	L"DðôY—uÃ–áH¶»ékñ¼ôZðL”ÔêL¸]ô^ô`ôaà½¶½á`¶¾›è¶ÁäÂèüë¹¶¿ÑtÕiÎ}ªšåL„E…X‹óž^™³šœ © Ù­{°òy÷ò×xØKÚGí~÷Çèoíbíüt×˜… ¶ÀóÆ¶ÂŽª¬o¶Ä¶ÃÓGÙ€ºVÜ¶¶Ê¶Å¶ÇŠ¶ÈÇT¶Š¶Éì|¶ÆÎ–š˜åƒÐCó¼‚Ç"   ,
	L"D‹e¶ËæH¶Ì¶Î¶Ï‰F¶ÐÈ˜é²ìÑ¬‡Äa´V¶Í¾„š¬óýå‘”àÜY»f…¶ˆŒ¶Ñ‰[Å¯yîXø‹çŽ¶Ó¶Ô¶ÒŒµqí¡êŒíÔ½˜Œ¦í­žAËcïæ‘»ž}×Bç…×m¶Öª¶Ø¶Õ‰•‰Ý“æª–‡“Ç Ôíâ¶×ÜHò—íïõ»ÜO¯ãçìÀ¶Üí»Þš¶Û¶Ù¶ÝâgîD´]ßq"   ,
	L"D—Ûv¶àßÍ¶ß„„“šÇñÖ‡š¶áîì„‹¶Þ”Ÿ”£”­¯kâ‡ŠZ„AõâõyèI¶ä–\ßá¶â’–’—ˆÊç¶—ÙÚrÜo¶ã¾EôD‡¾„m¶çãõêwð™ˆ‘Œ¹–ú¶é¶æ¶èÛFÛG¶åï˜ü‘†‰šùzÚàØéêæï¢î®îúâºØ¼"   ,
	L"EŠâ³jŠŠŠŽŠãåí¶ï‡êÞˆ¶í¶ð¶ëk›áÝ­«Óž°x±“âeï°¶ì¶ê´dÕMîP¶îî~ùZù[×F–•³Sæ¹òFùE¶òšx‘öêißÀ¶óÜÃêq…Ù³Xéî†@ÛÑS„þ¶ñ³bÍL¶ö‚­…v™³rÚÌÜ—¶õãÕˆñ¬ãµœŠÝàØ`ÝQß]¶ôŽþ“¬cëñƒiÎYïÉðÊÊ‚"   ,
	L"Eß{îOò¦ðIØ¬”AÓFÖ@ð_åŠöùšdî€™Äötù˜×†èyý|÷{ŠC¶÷ÝìWÞôíE˜s”ñ¶ù¶øõêzX›˜ÇH–éÃsÑLð¹»•Ý[öÜëXó’õbøÞW¶û¶úåÇ¶ý¶ü–êš¾çíîïðDñ“ËnßƒÚ¶þprÙ¦„n…þ·¡Ù@Ð^ÙEÔ àÅßíÚÀ"   ,
	L"FïT‰ü–ív–DîCˆóÙSªŠµpˆ©‚¿Ã^ÙH•\±}Ð““Ü–ÂÒUÅx·¢›o°k°l‘óŠ˜ìáe·¦·¥Š‘ÛÒ¯V·£·§–ì‚ë·¤²XÁPéyÁUËtá·¨íÀåzžž·©¬móŒ·«é·¬„å‡h‰“‹Ìá¦‘Œ”ó”õ·­·ªÞNïcïx÷Y·²„F„G…K–i–¯·¯»o·°Åt·³Åw"   ,
	L"F¹BâC—¡Ÿ©¾u·®Þ¬˜õìÜ­[ËX·±ÒT¿œÁ€õìž’µ\ÞÀçxÏ›ú‹·´¢’BÞx·µšï·¸Šišø·º·¹·¶··î²ÓŒÜèó±F¹DØœÝGïˆï‰J‹Ë¹ ‹Ñž~·½Úú·»·¼èÊ °îÕœEÍKˆÚâ[åpøh·À·Á·¿·¾ˆªöÐô™·Â·Ã·Ä•P•X­œ±f‚”ë¼ô³"   ,
	L"FÔLó„úJ·Å·Éåú·Çïw·ÈŠóŠôœdç³·ÆìéªUìqÑq¾pòãö­öîð[ñIòWòaöEïy·ÊäÇ•›ëèÎNÏn·Ë·ÌŠOã­ì³—’é¼ôäÊ„Õuóõ·Í·Ï–{·Ðáô·Î•h·Ñ‚n„|…Š¯XŒÐÈQŽüÙMðòïÐUÊ†•Õ°Cü”žO™¶çšì]·Ö·ÔŽŒ·×·Ò•S·Õ¸j¼Š"   ,
	L"FÁ‰—±ÓŸÜm·Óâpëƒ–Bðið·ØŠ}Œð·Ú–ŒžÇÃR—rÁiÍ_Í`èû·ÙÉkñBëV‰žŽËÊˆôšøX™JŸøŸþØk÷÷Á‚ü‹ØrÞMèMñOüR·Û²büv·Ýˆek·Ü·Þ¶lÙÇ·ß·àƒf‘Š^Ä¼Sö÷å¯÷a·á·ç§„K„NŠ~ãã›h„O·ã·â·è±`í¿ïLo·å‚ª"   ,
	L"F—Q·é¬S¥œtœ½ªhÝ×·æ—÷ È·ä¯‚´^ƒtºAà•äh™lØSæ‘çQÛºŒ›ž–ìbïpüK·ë’¸·êˆù½ ·ìÅ‚¿p·íÒƒßôÖS·ï·î®gÙºœ˜ŸuŸ‘ÚRøLøPøiÙˆÌX­žÒ…–ˆu—‚¼€ó¾·ñÀŒÀë€ø]·ò¸ß‘ß»Š•–Ž«c·ôN–´³QÇCÐuŠÂÇX”ê"   ,
	L"F¼”õÃáKôïïûõÆâa¹[½š·õ·óûŸ¼JüAüF‘ÊT¸¥·üÙì®iƒì„_æÚ·öÜ½Æ]ÜÀ…ò@Ž“·âö·÷·þ›Šç¦ç¨ÜÞÆ…·ýˆŽ–¢–Á·ú›šžÞ«s®t®wìðî·ÜòÛ®í‚øI†b–ó¸¡®}íÉÝ³ò¶Ùëèõ¸¢ŸJ¬M·û¹A¼›½EÁåõÝÊÌ’¸¤·ù½nÁJÈƒ"   ,
	L"F¸£»™½•Å€òÝ·øãRãVïOøD˜_·J¹…Ñ}íhá¥ºòðó‘øqÖDÛ~Ý—õH¯žõvíêùfù›¸§¸¦¸®}ÞÔ¸«‚YàM¸©¸ªáœ’Ñ¸¨—ÓŸr±G¸­äæ¸¯Ýoº…íë¸¸¸¼¸¶¸¾¸º¸½¸Àˆ}¸c¸·æâ¸´µyÓ‡Ø“¸°ÍbÐ•‚¾ƒå¸±Šï‹DÍk¸µ‹c¸»ÍÈiÍ|"   ,
	L"FÒ„Ôc¸³—Ú¸¿¸¹öÖ¶OÑ‡êç¾”ÊÎlòóÙxñ€¿`Ý•õVÙŽå‡å˜öû¸²ð¥övªgë¶áë"   ,
	L"G«qérøWê¸Ù¤‡QîÅæÙ¸Â¸ÁåmæØ«VÞÎôp¸ÃÚëÛòŠ¡YÇD•|êà®„µ‹Ô“ØdÙWÙ^ã¸Ä½iæYØ¤_„÷„ø–q¸Æ¸Ç¸ÈÈ‘â}ê®¸ÅÉw˜¢˜£[­y¸É¸ÊÆQÞ|¸Ë«\¸ÎÛáãïÜÕ¸Ì¸Íðáôû»ˆx„QŒ¼ÞÏ¹mlŒ¿ŒÀôv°‘¸ÑÐr¸Ï¸Ò¹C¶’"   ,
	L"G¸Ðä÷ÚséÏß¦º•÷ ÷hêº±Yí·ç¤‚‰ƒ÷äÆ½CÔló_ŽÖ™g¸Óž¸¸ÔÀ ƒé¸Õ¸Ú¸Ù¸ØŒù ±¯I¸×¸Ö„‚î¸ˆÕ’ââG—ž Âˆþ¾VÀ“ä“æs¸Û¸ÜŸ€óà˜í°¸Þ¸á¸ß°wó{éÀØº¸à˜°™R¸Ý¸âðp™²ízúküŽú‰ùê½Ç¶Ž¸ãçÉéÂªˆ¸å¸ä"   ,
	L"G¿cÞ»™…Ì¸æ„ÆÚ¾Û¬zµ†µ‡ï¯¹l¶JÕaä†¸êÛÙæü‘á¸í ·¸ç¸ìñË¸ë¸î¸é¸èœð‘ëéxømøw”RÖgøæŠ…Ïà„ý¸ó¸ï”š¸ñØªÍÅZ¸ð¸ôàÃÜªœèÓkë¡˜†ëõéwïÓík÷ÀÖYõs™ íuÞPíRòZöÛÁô´¸ö¸÷ò´‚€íÑ¸õ¹wª˜¸ø"   ,
	L"G¸ù¸úßçØ¨ôÞÝ¢“^“j¸ü„j¸ý®u›Ê¸û’ùÈ@—ÔŸ‰½câÙûf¾¿KÙs¸þùˆàQßì¹¡y’ªç®¹¢Çc¹£½Žöáóiõ†ƒˆí†¯†Ö†ñ¹¤¹­¹«¹¦¹¥–r¹©¼këÅ¹¬Œm¹§ò¼¹ª¹¨…@‰bŽ³ö¡Üp…C´bó•Óyý¹®¹¯¹°’–íçîÝ\ì–¹²¹±Ø•‘E"   ,
	L"GŸËƒÀƒÅ¹´Øþ¹µ¹³ÐçÃâh¾—Ñóôº÷¸íxá¸¹·¹¶èÛ«vÂTÂVóÑÂUØxˆx¹¹Ú¸¹º¹¸Š¥Æ™ƒÚ¹»‰òÔ_æÅì°“kåÜëgŸµêí“ÂÓMÙ¹À¹¾¹Ã¹Â¹Á›}–¾éï†f†gÁBð³¸š¹½ÝÔòÁÉuõýÝLÝM¹¼ôþì±¹¿¹‡‹²ºH™OõYøÝž÷½¹Åãé"   ,
	L"GÚ¬¹È¹Égêô¹Çî¹ÁlßEîÜ‚ï†˜Ã™¹ÆÍvŒ½ë³‘Ôbð ˜€¹Äü‰ØÅ˜b°–·Y¼MË[žJëûðkžk±Wî­¹Ì¹Êƒó¹ËˆØáÄèôêö—›µ¹Íðó¶™ïÀíƒlådöñöAî™¹Ï¹ÎÆ‚ëÒð»šOŸ…Ÿ°ïN„œ¾ äTøŽòmƒÖ…³ßÉ¹Ð„Ž†§¹ÑØÔˆqÚ´¹Ò"   ,
	L"G’ìÁGÁL¹ÓÔŸ¹Ô¹Õ–¡–Ê¹y¹Ös¹Ø¹Û¹Ù¹ÚÒ‹ÙÄ¹×ÉF¸A¯°HÓQ÷¤Ó^÷b¹Ý¯p¹`¹ÜÝ„Åoå]ð^ÜIøAš¯¹á›Œ¡¹ßÞèäÊ µ‘T“¥ßk˜ÀîÂÀ•æš¹à ƒ­µeðÙ¹Þè…÷}¹âž»ïžÓžÕžÖßÛˆŠ­ÆšèæŸD«‡ë×ƒZÝ_ã üU™õ¹ã"   ,
	L"GŽÚáî‚U¹ä“Ñ¹é¹çæ£¹ê¹æßžð§Æ—¹ëŽ¢«•w¹èÑO‹‚—Ë¹åàF“±é|öÙ‹¾˜²˜³­Y²nôh­„™Íå³¹ìâÑæØÐ¹îê{ˆ’¹ïÜ‰¹íŽëµƒ…QêÐœˆÍŠÓmÔŽ…‘óþÏj¹ôØÛ”Š¹ñêÁ”‹¹ó¹ð—Î¹KÙFÉ}¹ò²Z„£„¥“Ê˜­¶Wºl™™÷¬÷iÙò¨"   ,
	L"GçµÐ–¹õ¹öÉ€LÊFíÞÝöçõPõ…¹÷—œ²O­eÖßÃÛö¹ù†©áÆñøâu¹ø‰¯†‡H˜òååœ‡ë‡î‡ñ¹ú‡ó‡øàþÞâŽ½‘I“XÂƒÊbë½Ùå¹û«›ýâ£Ç‘ðŸé¤Ñx˜¡¾[òä¹üðRèJ¹ýèí¿©Ý¸ßÈ"   ,
	L"HðgœWØhØm‚sÄD‰™…Åô‰ í›Íìà@½wå”œ—U›N˜oÅVæ€•± ç’š¸ò…šã†yÁ‡ÔúX›üðÀâ’¿Sù]HÚo‚ëq›²Ò^íW¾iÄNÄs¼@Ý{ß^îþR¹þàËº¢º¡º£ëÜŸQ‰háVõ°º¥º§º¦º¤†ãï™ñ”ñ›‡¯ðŽaƒËÎñü†còÀº¨í™ØE"   ,
	L"Hº©ñHõA÷ýÚõº¬ºªº¯„TÍH†i‡öŠÎ›¿—êÏ—cº­ìÊº®²º«®]¹b ’ÎK¶äwín…{º±›Èº°ÊGØJô_ººŒå’Iº¹ê\ºµˆ¥º·º´•~›ÛªRÇt•ˆº¸¬HÝÕâFé\°y±Ž‚þÍ”ò¥ÞþÎL•ÂäIädº¶º³º²Î‘îhîuòAënå«ú[ôŒÆf”ãº¼ˆœç¬"   ,
	L"H¸‘º½ÍañþØ˜¹V½Wî@ãìÝïàãÞ¶¸hòººÁ—·àÆª|‡sºÀ‡_ª‚ƒŸ•Øº¿º¾å©»DÏ–×qºÃºÂºÅê»•a†ShºÆºÄ•‰œB‚Ûð©Â|Ì–•µ•¼»°€°‚°…ËA°ˆò«å°î—ö‚ž®ƒÁÚ­ºÇºÈÔXàÀÏšºÌºÏºÎÛÀ…ôºÍŠºÓPêÂ–­±A»tºÒ†Y”—"   ,
	L"HºË±BîÁºÉ† ºÔœzºÐ¶…ºÊÈMý†²»—ÔZò¢—æÔ†ãFãØ÷…Ÿ¿éuûiû¼ºKôçôŸêHý[Ò‡ùŸ°èYý˜Þˆ†ºØŒyŸZœ¸ÙRŸŒ´EºÖºÕº×ÂGÛÖ°F eúQýLìeìfûSìgü\ºÚºÙ¦‹Ï’‹ºÛì•äºÜºÝÔ‹ºÞºàºß›êÃ†Š¬aºãèìžî"   ,
	L"HçñÃtûaºá™Mºâø’ùCÞ¿èUˆý‡ÖYb…·ž¿ºäºåÙêºæÜŸŸp³…Þ°Ý“‡«åÞZ›ºëŠkºì…Æºê›K«YÀ€ãÈŒfãü«aÆyˆ˜Š¼ºé¸fÝ¦ºç›Ä¼‡ÁŠÂo³{¼˜ØAºèœ|¸s»ŽÈ‡Èˆâvéb½“ÁØD~ãpìô„ºCäfšÞ®ë”ÙäëŸø™üZ•{†ß"   ,
	L"HÚ§Ó“Ðµ¹äUºî³@ºíŽ«ºïÈ‰ðú²Tóóô×ÂF÷¿æAðfö\ºð êºóàCºñˆ‹áá›•åËºòàjÜ©Ø_ö×÷õ`÷cºõ…Iò®ºôˆ~ºö•U•÷›~Æ~ìÃéõ…Oßüã±œXÌÜ ëŒ‡FŒŒäïëišXàñ’_»¡ºü®@ºúºø‰ÖõúŸW†¼‰Ø‹|ºþâ©½`ºù—ýìÎ"   ,
	L"Hº÷‡PÊSðÉéÎ¹”ºýºûÐkô–¿eÎ™õ­îgì²æLðbž€ôEö{ù–úCúK[›R»¢ä°»£ÈLçúÌ•¹}åtöU»¥u‘ô»§‘õÙüƒêŽ»¤›Z»¦á²âïìæ•O–ìïóË»‡Šýìèð­½œà‚‹¬‹­“ªœûÊd˜«ŸÚøUºnåð××o÷Ÿí_í’÷sûI»¨Æ_ˆµ‹N—É³“"   ,
	L"H¼AÕjåkÌf»ª»©Š£æèîü»¬»«‡W“ç­LÎ”çfò‘ú†»¯»®–»­»°†èë‹O®‹‹Ã®“Ô’„“®˜¥˜å‹½±Õ–Õ üXÀEÌs»³»²»´»±Ñ‘õ×‘¯Ñœ‘Ñ™ÆÂjÌx»µ‰²‰ÄÌ|»¶šZøb‡È‘×âµšgØŽ×’óO»¹»·`ä¡ÇB»¸ÈPÝÈˆâŒ~½bëfÁvØ}"   ,
	L"HïÌêaå¾çÙ­hØoæDûq¼]ÀQÞSêX÷ß±»º¾”k»ÃÛ¼ÃKŠJ»Â»½»»ä½»Ážð»¼—h»ÀåÕ†¾´Ñ“Qœo»¾Ÿ¨¬~»¿äñ¯ˆ˜¬öéß§È²oËõŒöZödŽxëÁ»ÄÐY‰E»Å»Ê‚µ»ËÚòüS»Æ†Åˆð‹h¢áå»ÌäÒÈåØ˜R»Í¬‰‰ŸäêªéBŸìè«"   ,
	L"HóòÅŠ»Èñ¥»Ç·kÖW»Éó¨å–ðcöüÚ‡çuòböm÷UúŠU»ÐžêŒr»Î•sŠN»Ñ»ÏéÔ…¿mÖe™¤°ŒƒÆœê˜n•Í°æw»Òž¾Ú¶ßÔ»Ö’’»Ó›‘ò³êÍŸFçõØYŠî‹^“]Áš»ÔëD•Ÿ—ò¬qµ˜ÔœŽ¹²N‡j‡vÂEÝx÷â»ÕãÄž`ö™‡ß»Ø‡éÝhjo"   ,
	L"Hä§ÜîÞ’ŸCßD¯`»×ÍzÍ õt»ÚÎšš«™m S×e»ÜŒá»ã»á»ä›xßÜä«»æÆUÜö»åí£{»â»ßåç»Þ»àà¹»Ý½}çÀÁ™ê_…R¡¢š§»ÙœóÔÙVƒa‡GÊ]ÕdˆHŒ“»Û‘}•Á˜žŒÞ¥Ú™Bª›­_ËCËDÖMî_™b™u Zº_Ë™ðd‡¤‘Î²~·xÀDó³"   ,
	L"H™®ÀLÂP×MêTçžìu×wîœ»è•e»ç»é›÷ãÔÇ—•²E²Jé’ù»ëâÆœ†»ê¿Œý@Ú»‚[‚“‡õ’ä»ìŸkäãùÓoÕŸ…¿ñëïÁØååx»íß«òdå»î¶»ð»ïß˜îØâ€â·›[»ò»õ…ü‚i’»±n»ñ„Š»öØ›»ó”üœ­µœ†ØŠ_žC«@»ô™ŠÖf·‚ïìàëžm"   ,
	L"HÂhÞ½ó¶‡É•ëÅG°\²‘èZ‰þÐÐí¹à÷"   ,
	L"J°nóp®‚¹kºu¸’Ò—˜È¼‚eäzërÌŽÕ‘ˆôÏ…Ó]Æ–Œï¼vÑ\˜‹ïW‰ø…¨«EÅSÅQ•Q÷ZŠoˆðš¼tùJØ¢¼¥»÷„Wß´¼¢ØÀ„Z»ø»úçá¼¡Ü¸í¶¼¦–ˆßÒ¼£ØÞßó¼§åì»ýóÇï|»ù¼¨†À³ïúê÷¹U¼©êå„Þ†æ»ûõÒøKƒ_»þã‚‡\“Ä˜œ˜Û"   ,
	L"JçÜ»üÙ}Üuì´ÛÔ‘¢™C¼¤­^·eåZëY´‰ºs¿ƒî¿ÙŠ™›Âfëu×Ií‡ù×^°^ÜQíZúaýVÁaÌ~èWÒˆèiýWÁbûAÒ‰‘¼°³¼ªá§²î¼³¼¶¼´¼«Ø½Ù¥àB…u…¯Š ¼±ªE°uóÅ¼‰“V¼²Óf‚Â…hŽóÃØCê«¼¬˜Oéêœ–¼¯‰J¼µêé®ÝðÎa"   ,
	L"JÚl¼­˜ŠÂcÄlãšŽNñ¤¹œÊmÞªì“ûn™W™vÎŽÝ‹ÒQÛˆå‰Å¼®ÞUçgìPúWúnë|ë}¼¸¼ºMŠj ä›‹ò±¼·¼¹Þá÷‚Ž×êªáÕ÷äô‡“Ø”D·mŸ”ú¼Æ¼Ç¼¿¼Íˆj¼Ë¼É¼¼ÜÁÆa¼Ê¼Á¼¾ßâˆ…c¼Èä©¼Ã¼oÆˆÓ‹„ˆ¼¼ÌêéÓ›ÙÊ¼Å¼Ä"   ,
	L"JÂ¼Â”û—m¼À¯ÅUÈ—ƒÎ¯s¾@¼»Ñ_ÛEëH‰€ôßPT¶I·I·bÕHõÕö«öÝ•¸ð¢Õ‚öê¼½„©•Ì·]ËEÒH÷Ù™o¿ŽÁYÓJõJ™‹Û”ùHýT^‘Õ°U¼_ÌRæ÷õŸž†À^Ìn÷DÌzìVö›÷C÷qóK¼Ó¼Ð’z¼Ñ›våÈ¼Ïš¹ä¤çì¼Òðè—kóÕÂ_ôÂªoÝç"   ,
	L"JõÊ ÇÄ`ãe¼ÎïØ¼OØjØ†æ‰û“ˆ]’SáµÛ£¼ÔàPí¢Çvê©îò‘æòÌ¼ÕÍÛOïäeî]îaø”ùG¼×«wëÎ”Ï¼Ö¼Ø‹T”Ð—ÝÙZâ›˜\˜–ðý™x¼Û¼Ý¼Ü¼Ù¼ÞŽ·˜k¼Úñ{†íê§¼é¼âŽÔ¼á¼ß¼äƒï‘â¼ç¼èŠ¦Š§¼æ¼àˆÔ½ª\¼ãÝÑÈGäÕ  êù"   ,
	L"J¼êÈ‚È…égÞö—ß¼å¬{²RçÌÝó¹{˜ÙŸÒ¾}ÊzÊ—öäðÏŸæº]¿Vä’ÆDíKñJû…žh÷µšµMÓVùpžŒšž»Wí[öž‡ØÌ‚ídàî¼ðèÅ¼ó¼í¼ë‚›’³¼ñóÈ¼õ¼ô¼ìœ—õÂ’þ—Êœpíú¼ïñÐÔdïµ¬‚¼ò½€ÚÙ”‘ìê¯¼îƒ€ôå™zËuÒMÒOåÀå¿"   ,
	L"J²€º†ÀOÖˆôCörûxžÏ•ç‰ç™û{×vÒ}û|¼û¼þü½¨½¤½£›–êð¼ö¼ú‚k½¡„‡½§«…½¢„É½¥ÚÉâVŒ{”ðé¥ë¦½¦ëìÅ[¼ùÙ`¼ø¼üÙÔ˜c„¦„§‰¤¾¼ý¼GÕÙvÚ{Û`õÝ„ª„«™ZË]æIðT²{´´–ÏMæG”W¿ ÓSÅžÞYèaèbè{èƒ½­"   ,
	L"J½ª½«Üü½¬®{ôøÈwÁž½©{Î…‰¬çÖËK™^š™ÏQ÷š®Ÿíä½®ÀPí\÷F½²½±½°‚×½¯ŠXŠ\ÊY˜ªª„ñðÄvÖvîŽ…G½³‰áx–t½µä®ç­‰ÑH½{®–½´“À@Úêñ¼TánôÝáu™ºÖ˜Ü´ÆL½»½¼æ¯½¿j½½Üú½¾½º½·½¹òÔõÓÙÕ†ýÌ—öÞ‹É"   ,
	L"JõŽB‘xÄz½¶Ä‰½¸·põoðÔºŠÏtç€ú„úŒ™ËÅT½ÇÙ®ÞØ½Æ½Ê½È•w¸‹ð¨½Ã½Å½Â½Á¹R½Ë„àë¸Ÿ”Ä_Ù]“¼•¯Û]ãqïœƒ‚„¤“èáè”º”¼½É•Ý­d³C°‰ùa‹ùÀq”‡ž«÷R½Ð…Ó’›ÓŠ«„½Î½Ï”œ½Ì½Ñœò†û‡U”Ò]½ÍàÝ‹Ðª—ËŠÚŠÞI"   ,
	L"Jõ´×_°á†½×ðÜ½Ô½Ó’÷¯^½ÕëAà®àµˆê‹m½ÒÃ½ÖŸ®·MìŒÎf“ø°Xù™æÝŒ¨½ÚÚ¦„f„g½ÙŒî•M„o„Â½ÜÐwÚµÞ×½à½áÞ—èî—AÇ}Ó“æ¼›½ÝÑK‚Ü½Yò¡Ë˜Pœï½Þ¹ÍÔ‘ã]ô‚½Ø˜míÙ½ßÉ•öÚôÉÕmÛdŽÑŽY”Oµ@æOŽ^™Ã"   ,
	L"JÏÏ˜ÐV½ãš²‹d½âï™wN½éŒôŽàð½ä½æŒÃ½ì”â«d½ç®v½ê³VÐ|½ë½èò»Èˆû—ô¬pÍŽ÷º ÏÕ]Ñ›ô½å½í½ñ½ïîÄƒ»½ðáŽ½òñæ³\ñÆÓb«ƒ¼Ž®¬Qˆü¬n½î­\ûvüT½ó½öÚáŽ„½ôÝÀÇžƒH½÷½õ‹¦âÛW±M¾oÉ“âËéÈèªå\"   ,
	L"JÖ”ð~„³¾¡¾¢æ¡½ü½ø‚B–‡„Å›»Ý£•x½ú½þ½ýêáµ‰ßMŸ¥çÆŒƒ“|œÃ½û½ù¬’ƒq„Bšêîƒàä¿NÙ‡ž‰½‹âøË| a­nÓPÚBý„ˆi¾©ãþ¾­¾¥Š¶p¾£ÇGŠù¾ªìº”ìªS½UÝ¼¾§¶“ëæ¾¦¾¬½›¾¤¾«Â€™Y¾¨ùXöLù~ûü ó@û—¾®"   ,
	L"JSÚåØÙŒc›G›HëÂ„q·¾±¾°ÙÓŽÁã½­E‘ •Ç G­Z­`îiÏ‚¾¯Šn¾»åò¾¶åÉ›·ëÖƒô†½¾·¾ºÞŸŠøæº—J—}œQ¾¹¸x¾´¯d‚ý¾¸¾³â°Õe¾²îK•ß¾µìožsçR¸‚¸„ƒÕˆsìçˆ·½Nñoñ’ÌSƒ×‡ååÄ‚C¾¼Þ››ÓŸKŸ ¾½ïG½ŸƒTŸ¡"   ,
	L"JŸâ° EÑ•ÌWL„ó¾À–`¾¿¼jð¯¼môñãÎÈ\à±¾¾“[÷Ýôb¾Å¾ÃX`Še›C–w¾Ä¾ÁÅi¾Â¼‘¾ÆéNíƒ…E¾É¾Ê¾Ì¾ÎèÑ–Í‚wèê¾Ç¾È¾ÍŽý…B¾ËÙÖGH‘Wš”ÅfðÕöJû…Yýnú™ã„H’]„û¾Ó¾Ð›t¾ÑÜÚ¾Ô‚˜’±¾Ò¯YÁDêŠÛŠè"   ,
	L"J‹J‡Þä—x›ôé§è¢ÄKï¸ñÕöÂÅ‰ÎAÕ‡Ûgä|ñxø~¾Ï÷¶ù‰¾Ö›†‚I ó½ÛšÁœHŸh¾Õà`—»šÆœ¦ ÊÝ]»Üvé…éÙ™hñùVÛžùqŽeÌ^úGóM¾×¾Ú¾Ù¾ØÜì’¤—º¹_é·é°ÉXö´Â‹Åeõá”H™Î™ÛÒz¾ä¾ÞÚªŠŒøþ¾Ü›®ÜÄßš¾ß’‡•Z"   ,
	L"Jšj¾æ¶€îÒ¾ãÙÆƒâ¾ç»‰Â`ÍiÐˆ¿ˆÏ¾å¾ÝÔn¾àŸqêøâ ì«Ì˜Øe¾âìñÀ¾Ûñu„¡„èåð¾áõX‰±‘§“þÞåáäŒÕïZº–ÜMõ¶‘Ö „Š¤¾ê¾èä¸ÑZ¾é„æägïÔæŒùNçîÃ¾í…ÛŽ™ˆ±ÇšïÃÄ–äŸŠF„»¾ë„Ìèðáú¾îöÁ›û®C¾ìÛ²±’"   ,
	L"J½vÁI²C‘gÊ^ðCÁ\àÙ¾ï“ÞŒÖŒØ|ŒHæÞ¾ö„]šÜ¾÷¾ñÆ`«i«k’¢çå³O¾øÍD¾õ¾ó™þáÈ¾ò”Çèöš€ÒõûÔEÚbÚ‘ØÊ½^½~Ò™ÚkâfØã¬œÚÜŽ@ŽD‘•ŸØ “â±¯‹Ê…Þ§ø_ø`‘‰éÓ™@éQ¾ôÄ”ïãÏpÏq u×HõêÜB½ÀÛÇÓXçžŸìßÓ"   ,
	L"Jž‘Ý¾ð«Pú€™ê²Ÿý™Øè‘¾ü¾ý¾ù›JÐ‚ÜŠ¾ûÇqÍS—Tñä¾úâx´AóÞ°—°˜ÒŸãzã—÷÷åå‹õz…Í¿¡¿¤ê}ˆ­¾þÞÜ•€¿£ðž¿¥¬B®¿¢¹‰ÎDƒyŒ”‘®ðKŸóòEùQùRùUæùÐ®ÛÈ"   ,
	L"KåHÌžGóaŠR†Ë‡iãs–FÃdêl˜‚·XË›œÏ½\öŠ…jO³qVÃvÄ„šw—ëãxŠsË^òÂšÎÐŽýJm“‡ÈA´hÊy•þÒ­gðQ¶„t±O×t¼÷™‘’¹“×…Ã„ÛVñißÇ¿§¿¦¿¨ØûˆšëÌÑQãl¿ªŠK¿«Ð_ï´ç˜¿­ØÜÛîâýê]îø„P„’¿®ÝÜ‰Nð¿¬"   ,
	L"KÝa•°ïÇå|æzêGïaâéžÍ™üžý„Ñ†þæbf¿¯–Ý¿±íè¿°ê¬ýƒÝ¿²Ù©¿³Ý¨‚°§‰dÝ|¸ƒÞR¿´Ðb€‰{ãÛî«´|²™ý³T»~¿µ‹¢Ü¿¶o˜±·^¿·Ü{ç_÷K¿¸“•¿ºØø…Hß’‡ã¿¹ èãÊ¿»îÖâ‚é`åêó}”Ž¿¼¿½›Ÿèà¿¾îíêûäD÷Š"   ,
	L"K¿¿õwõ‘…\¿À¿Á¿Â ˜çæ¿ÆÃméððâÚîÝÁ¿Ã¯zÈdÝVò¤“t Éïýñ½âŽ˜}ËP¿Å˜Êî§¿ÄòòîWáfîw÷ÁµL¿Ç¿ÈÁ˜ŽP¿Éá³žÜœfº”¨¿Ê¿Ë¿Ì„w„Ä„Ë¿ÍQã¡ŠÄŒ¡¿ÎˆÑë´æìç¼à¾ÚäÛï¾´R¾~Õnä˜´žòSÃG¿ÏÃ\¿Ñ¿Ò¿ÐØc"   ,
	L"K‰¨åo‘©’õñÌÑy„´¿Ô¿Ó³n ¾ï¬³™ÕUäLå”çHŽ|g†{…ž]¿ÕÙÅˆÂáÇ£³œóíÜwåIùy¿×¿Ö¿ØìW¿ÙÜÒíî„›“²g¿Ú„¼ßµ¿ÛD””ƒãŒt¿Üâ@·óØAÊfÞ¢²]ºpúdØÚß ¿Ý¿Þ–öÜ¥‡ýÚœ¿ß÷¼õpª@¿à—ü¿â‚Vç«Žì¶s"   ,
	L"KŸ\ÑFà·½f¿ã¯‰¿áÑ‡¿¿äŠ¯Å~Ù¨†E¿åã’¿æ¿è¿çógØá“ùŽw„SˆQ¿é¿ì¿ëÛ¦ßàáöëÚ‰K¿ê÷Žƒ~à”XªœÄ’”÷¼[÷d¿íŒˆŒ’÷Åèwóy—p¿î¸T¸U¿ï„ÁÚ²ß…NßÑb›¬¿ð¹nÕEÝH¿ñ ïÚ¿Ü’ÜœÕNù\ÞÅƒ—‘ÈÚ÷ÛÛæþ¿ö¿õD"   ,
	L"K›r¿ó•pêÜ¿ò±q³m¿ô½T½_ÙLÝAãkäqà—‰¿üY‘Ç•ç p²ŽµV·ƒÀkèk¿÷„l¿ùã¦¿ø¿úÂ¸QÌêNîÌl¿ü•uåÓàkí–Ø¸à­Þñ¿ûóY‘èêÒ—ó—õ¿ýî¥òñî`™œËwåžæKòjÙçÌwÌ€Üi…t¿þŸõÍíŸÛ“ŒºØÑšCà°‹ã´À¢À£ÝÞÀ¡…T"   ,
	L"K‡]‹Å‘|óññùÂ‘Ê‰˜æš•ðrºˆÂ˜»Açqè^À¤À¥•‚ˆÒˆÜ‹GŠ‹ª^ÇÑTŸjçûó‚Ñhï¿÷ÕûdŒ±„ÎJÑ‚óˆŸã­@õ«åKöïÅCòOöHù{úAã§À¦ãÍ‰×—yµŒ³¶‘ÑX‰Ú¶Ÿ½™é€éÀ§›Ù±—À©’ˆÀ¨’•èé—I¹QÈuÈvòÒÀ«ÀªîSžNéŸíA"   ,
	L"Kíp‘²ìHíTôU·i"   ,
	L"LÙû„Ð»ŒÕvã‰Œ™ŠÅˆhá”Ô›à~ÄwôfÆŒÍxækãtÁ}ºT±šÄBÌkØF¯•©“ìÖG‚Šö¦ìn ¬“š˜Í®oŒŠ¸MÀ¬À­–¬À²ÁÇ‰ååê¹íÇ“X´rÀ®Ëˆ‡ÄØÝœ¼À°“Y—ïðøÀ¯Î`ÞhÀ±Î|Ä—”j mÅDôF™Ê­†éJö_ÏžèníBÀ´í‚g‚|áÁáâäµÀ³"   ,
	L"Là[‹@ˆŽòÆ—…œZª[ÈRßF—®¬[¹Xïª¹sånòQöDù„üH†‹êãíù²AÀµÙläþÙ‡îmîsñ®ù`ž|žô¥ÌD°]Òs»[À¼á°À¹À¸À·¹ÈŸÀ»À¶À¾À½ñÜƒ‹ìµÀº LË{Ò[ïçê@­sÒh×EŽÓ”rž‘ž™»@ÀaÌm”Ì™ÚµfÒw‡Ûž±»_™í×ŽÜ_Ò€è|"   ,
	L"Lè”íeÀÀ›ÇÀ¿ÀÂé­äíî½áY‰°ÀÁÓE”G‹ö‘Ð‹ûÓ[ŒG”ˆ™ì ŠÀ|ÀÃÀÄ A‡•žE f € ˆ­Šž°¼hà¥„ÉÀÉàOšDÀÇÝ¹‹™ÀÈ—OÀÅÉvÀÆ¬˜³„ïüï¶¹^Å…Í™àHòëÜqäZæƒò@”ÀÊãÏ–JŸR‰iÉ‡˜¸ÕLé–Tˆ°ÀËÝõ†}ÀÌ»”“ÆÀÍ„ºÀÎ"   ,
	L"LªJ·†[ßëáÀ›Ð„Úðìï©ƒX÷‘Ž–U°A´‹ºŒÏoõ²ç„î‘ó€ÀÏÀÐ†KÀÑ`ÇNèá«™³zîîÍŒã™ÁÊ˜÷õuÞLÀÔÀÓ†ëñìÀÒ‹ª‘³™QÂgÜ~ØìêbÀÖß·à’AšíÆI«Wãî¸…³iÀÕ˜Sí‰º{÷¦ö˜ð›ðEÀ×æÐçÐÉ ˜Ã®šéÛ¿wÀØ™§­zÙúµW"   ,
	L"LÀnÀœÌrèDÞ[‰ÍèhìYÌ…÷m™ïÀ}ýF…ŸñçÚ³ÀÝ‰C½t‚ñÕCÀÚÊu´ÀÙÀÜ‰¾°NË‰™¦²µXž˜ÏœÌ{×|ƒ±èˆûPÀßÀá›¤Àà›æœIÀÛõªãîLî[ÀÞåG”b´ ïKîÀhÌq¶aàÏÃšÜ¨ÀâÀã´G¶ ÛkËJÀä‚’ˆÙã¶±œ†o„^Àå„{ÀæÀêÀëÇV"   ,
	L"LÀòæê“—~ÀçÇ—à¬—ˆ Àð¿„˜Àì²@¹]çÊÅƒÝñòÛæËŒV˜»Á§±L¸{¼HÊkÑŸä‚öâÀèÀé¿rî¾äœÏ[Ö‚ár‡­Þ¼ß†ëxõ”ç\öPùv÷ó‡Îž¦Ìyó»ÐGŒCc„°èg·ˆ»hóP÷~ûZÀñÀîÀïÙµbÁ¨æ²q›ÉåÎÀíÑeï®»šÑYØNä‡Àðå¢¶YõŽ"   ,
	L"LÏ~õ·÷¯ßŠ÷k™ðÁ¦ÀúÀ÷ŒÞÁ¢Àô–^ÀöÀûÀøß¿ÛÞÁ¤ÜÂÀýŒüìåèÀðÝÆnÁ¥ÀþÙ³–ÐèÝðß³PÆÀóÚ\éöÛªŠÚ—Àõ–Û–ï›ãáû«†íÂÀù¶wÝ°à¦‹KŸ¬PóÒÁ£ôÏÍjòÃÀüƒú…—˜Á¡ÍîºõÈö¨‰Wü“…äàÉTÉWãWøE…“…–•·šs¬—"   ,
	L"L¾FÎG„î•Ñšvóöë_øtŽ_™‚žW°O´•ë`óœƒ¢•å™ª i Ø¶]Ï‹‡³‰È”ižr­|µZËž™À s­‰°±Xµ[¼cÏ ƒ«°[µ`úbû•‡ÑÞ]™æ×Þ^”‰­–ìZ÷uìc­€Á©‚z‹¼ÞÆÁ¬Á±Á¯Á°Á«ßB—†ÁªñÍŽ†öÁ®‘XiÉ…UŠYÒœ„ …V‡t‘z´nÂŽ"   ,
	L"LÂÑžöãå¥ï¿€ÂIÂ’ËOÎ‹™¹Â“ì¡ÛšÖ‹æ`Á­ºŸó¹ôHç ö–»^»dÁ²çöÁ³ñÏ“¢˜­IÝü‹Õ”¿šaÄ˜à˜ÒcÁ„Á·æ®Á¶Áµ›Ëéçˆä‹tœ‹ÈjÁ´ƒIé¬Ÿ’¬…äò¾šÔåbššå€æœž‡ön‘ÙÀ~º|Á¼‚ZÁ¹Áº›öé£ÞcÁ¸Á»Ü®¾HõÔ˜ÅÝˆ¼Z"   ,
	L"LIÁ½ƒÉ†|†¤’ëÃžÑo¾nÎW÷ËôuÁÁ†]ÁÂÁ¾†ÈÁÀœ´Á¿Ÿ´ÝgÕÝvåyÜGÁÉÁÆÁÄÁÅÁÈÛÁÎ‘lÄkàÚ‹»å¼ùú‘’ÁÃ”¶â²çÔß|•ÅÁÇ­V¸NÄ‚¸XÁÍðÓŒ×\ºƒÏiØIÙ’ÛŽ rç‚ósïmúîÉá‘à€Þ¤ véRÁËÞÍžÒÁÏŒ®ÁÌ²tßÖš¸"   ,
	L"L’£ˆ´ÁÐÁÓÙý„ÃŠ²h’žä£Æ”Þ˜Ûø›¼ÁÒŸIÞæÁÔªdÍ}ÁÑŸ­±ŸÂ~ôóŽ{ïVƒ•õhø•”Y«C ÚõñôQ÷à÷vÁÚÁÖÁÙßø…°ÁÜ•—ÁÕ»‘¯r´@¹ƒôÔàëOá×«ªåà”Ý•ÉŸû­Uê¥ÁØî¬Á×ÅR¿šÂLû‹ÞO‰ÉžŠçlÁÛò•÷ë÷[ÈHz·Aƒj"   ,
	L"LÁÝ„C“Ô[âÞ‘¬ãÁÅ™_éÝ°R°SïCÁßt‡ÁÞŸiÙUÝþ˜ð®Vì¢éŠ®žÌAÜCõïÜ\ÜkÞ`ÁàÁæ„cÁéàòˆ{‰çŠ–ÁëH¶ãö ÷Üß•`–EèÚÁáê²Áè°s³g¶{¸nÁåÁêû_Šê’’èèùœR¬O¸ ½@ç±ÁçôáñöÅzÁâòÈÐeµ’ÔfÚšÝCÉˆÑkâ"   ,
	L"LéqÁãÁä¾cÊCÝsë‘ñ|ÎÊ™ä™ë™õCöìøoûw UëëžýhžƒÛ¹öN‹øÌhýg™Ðáì`™ô ‹û™ý’êtÐ‡ÁìîIŽXÁîÁíßÊžâÁïìÖÁõ›f®qä¯Á÷Áô”éÁð®‘ÁòÑ^‹ˆÍì¼É]ÉsåÞÁóæòÁñ¬Šïv„¢¬–Áö´eïÖñ‡ûm˜ñ­]®œéH°@ÏYñœ‡®"   ,
	L"L‘ËžgË˜öÌæyðsûˆçBïdçsòtïiö†úVò˜Áø–Î—B«€—Pç¸ï³¾^ŸÞÁSä™PÁ[‹ôÁùÁ’‰gA¸´zðÒÛ‰ìCëwïfôjúw®F®M‡ÞÁúŒâÁüãñÜ×•oèÐççëÊ±€íÃÁýÁûÂ¡œ¬ð˜™VñªÁþº\‡µŽaŽbÌdçXìN•î–V™É z­‡²”µaµbÒt"   ,
	L"L»\Ã@ÐFÐHýŽØLÜ[èxì_ûTÂ¤Â¢ÛâÂ£ƒ¥ë]‰Å‰Æ”n¸_†U—Y³ŠÜÚLÂ¦ÙÍŠäà¶œ¾ÝäƒEÂ¥‡DI‘fÊVßs˜ÇŸÓñïò÷²kÂeÅ”ÏNÖŒÜ}÷ÃíVótáÐÂ§‰vâ“§U®RÂ¨ºtÂªŒÍÂ©ðüïÎ¯›¯œçUÂ¶ààß£‡£”]Â¬Â®Â«Ûä–›ãòÂ¯èÓ"   ,
	L"LëÍéñÅyðµ«SôµÂ­â„öÔô—±R‡´‰À]”mžo«G­oÌJ™¾ t­ˆÅF²’»VÀrÀžÆAÐBÞ_èzïBóz÷|ûRüuÂ±Â²’ ’ÇÂ°ûu³”Â³Ì”‰oFÉ˜ÄÂô”“ïéÖ´{ïåžZ™©šÚÅ›æ”Æ@çœèuˆP®fÂ½ôˆv Â¼V„ÎÂ¸éûê‘ŠáœGœOäË³tÇŠ"   ,
	L"LåÖÂ¹—¶¬fµ“Â»ƒJ„—„ÛÂË±J²FÂµ¶˜ÙTÂ·‰nL“¦äõ¹‚»œÊIÂ¾˜ÌŸÑÄrÄyÓtÚ€Ûjê¤áXÂº·cÊ€ä›åhåjè´óüÏFøšžVº˜ÛÞAòJðØºŽº—çGöIùcùnÂ´çeòƒ»UÓ€Ìú˜ëªÂ¿ãÌéµé‚ñeÄ|™°Ëƒ•ìúyóHÂÀ…ÎÂÂàL‚HÂÃ—o"   ,
	L"LŸfµ~ïùÂÁÂÅ½…ÂÆŒÒëöÄoñÚäXÂÄÒ@ƒ–·t¿|·„Œœˆ‡ÂÉ†`ÂÇÂÊÂÌ¯ÂÈÈ„¾G¾v‘]¹˜„í¿†™¬ lèrÂÏÂÍÂÎèïð½ÙõÂÐöÇùFˆJŠaŒDŒ\Žn”•ð™èž¤ÁcÅLˆKž´Ì‰èŽ°f°gû[ÂÑÂÒá›yÂÓÂÔ®ˆï²ˆGäsäxÂÕ’àÂØÂ×àðÂÙ"   ,
	L"LÂÚöÂÖ‚ê‡÷‹E‘¥œSÇ’—‹Ä@´K¾]ÎFÛiÝ†´ˆä—öM¶—ÂbÂÛˆÀœÓÕ“ÞÛîb‡ÓÂÞ†ªâ¤ëáÂÜÂßé¡ÄTÂàÂáÂâïÝÂÝÁ_ÓTæ ƒ¬ÓZò…«MÌ}ß‰™åúŸ»jèŒð”òŸ„sÙÀ³`ÉzÂãÜsñ§ÙùÅI”{•ï°eãøRÂåÂçÜýÂæçó¹J½jÂä"   ,
	L"LÞûäð ÎöÃñ˜õiùBÀz÷w"   ,
	L"M½]³‰Æƒ ¤ÔN£†OŒ©Œª –ˆbß¼“áÁo¶mªCØ€ºÑœ“¸š‰Ø~šÓ Ó…›ýˆý‡`…ÞÂè‹Œ‹ßæÖÂé¯q‹°Êh Ðó¡ÏWÂíáïÂêÂëÂìñRœÔªwßj¬”´aÎ›æ‹úiö‡}è¿µléUÂîßé‚Ø²K‡O˜q¶MÁRñˆµTôKÂð†áÂïÂñö²ÂòÝ¤ÙI‡XÊ{ú”"   ,
	L"MÛ½ÂõÏ‰ÓÂóÂôÂöÃ}ûœÐ]„êÙuß~ì@ìAò©î”Š›ŽÂù‘`“¶Âø˜ÑÂ÷²m÷´ðz÷©ôMôNö ÐUŒÌœº±”ÂúMòýÒZÏ\æž²–ÂüƒKÃ¡Ü¬á£ÂýÂþªƒçÏÊAÂûì×ÙïÜ¿zÏTÖ™çNÌp ¯Úø…¹Ã¦šûÃ¢–n–xÃ¤……}¸ˆÃ£†WŠÁ›À ½íËâI"   ,
	L"Mèš¯gÍ{ä€ñ ÌMÃ§ÇƒÆŸ‰ÜäÝòþÏ‘„õÃ¨ØˆÃ«Ã¬–‰êóÃ©ì¸œ~ÜšáFòÖÃª¾ˆ÷Öòúå^ó±ùšƒÓÃ®‘ùá¹ã÷ÜâêÄÃ­¹FÉ‹ãTƒÐ°pÆdƒØÃ¯Ã°±gÃ³ë£ÙóÒ‘‹uÃ±ÙQà|Ø•§—ûšÊè£î¦Ã²àŽÎcí®†xŽÛ‡¡žQ‡¼Ã´°Z›]Ã»Ã¶ÃµÆ€"   ,
	L"M–ÏÃ¼ÃzÝ®Ã·¬CÃŠàdˆõÃ½áÒäØœŽâ­±ŒÉBé¹˜MÃº¬s¶CÄP‰r˜ŽÃ¸ïÑðÌäYÃ¹Ûæ[²‚”uÌjúB”|üqš°Ã¿ƒñÃÀ’¯ä¼‹Z±œ„‹‰Ã¾‹Ê BÜzæVüeÃÃ’{›iÃÁµ|ñÇ±tÃÄÃÂ¯cÚ›ômŸ¢²S÷È¹ŸÎn‡ª—ÈÃÅÞÑ«fîÍéTéY’ÐÇ–­J"   ,
	L"M·`å{ÌŠÃÆìËž•¹ Fí¯‘¿ÃÇ‚ƒ’ú”BÃ¥®mòµƒáŽíÁEÃÈÈ_‰ôœÉÃËÝùƒ˜ýÞ«ÊpÎ{à‘à–ŽÌ‘º÷«B•äëüÃÊšÙ²‰íæõ’ô¿ûs²“ìXðîŸûLÛÂÃÍ®HÃÉÃÌô»òìåiãÂó·öQü€ÃÏÃÎ‰õ‘¸ìDÛ_ßä²[ƒßÃÖìòÃÔâ¨ÃÕÉoÔ™ÖiÃÑ"   ,
	L"M”CÃÓ÷ãû†÷çÃÒ«Jû” †‘Û”}ÞÂá‚áƒûJáˆÃ×ÁdØÂñåô›¦ôÍ»…ëßÃÐœ}ÈŽÎ^ÊUãŒBž§ôéãèåµÃÚÃÙaµzŒsÃØÃÜœPÒ’Ò“ÃÝÚ×‰QŽ¶Òšà×˜aDeŸÇÊZÃÛü†ƒç˜ÆŽÈóËzÖk™—º€Á]ÆPÃßŠåÃà‹iÃÞ¾d¾‚ÅXÎe‹î™†™¡"   ,
	L"M²Š²Œ²DšóÃâãæö¼‚aÃãííÃä‚ÁÃá„Ò†»ÒäÏÃåÈxëï¾’õ|ìrÃæ¼Eû ü@üMüIß÷Ãç‹bÃèÃéðÅ‹·ù‘÷]èÂíðÃëíµÃìç¿ºF¾˜ÃêåãÃîÃí¸kŽøR…¸ßã†_ŒPÃð“}œçÃïËIøpŽÏ‘Ìžfóú™­óºÐ`èf÷x­ŸÃñˆ„Š“áºB•F•G"   ,
	L"MçäÜåçë±aƒäÁF‰’Ï¬Y¬\çÅ•¡¬z¯x´CâŒ¾r¾‡ä æFÃóƒí„bãÉÃòãý„Ç”•ÃöÃõÃô¸œ¹Iœ¡éhíª”°üwé}ƒo‘O‘‘˜º‡÷ªÏŸöšÃûÃ÷Ãù›³±bÜøÚ¤–L±…Ãúàp‹“äéªuÉqêÔ˜iã‘øQî¨ÃøÓKâŠ±ƒü‘Dõ¤Ãü’øÔšÃýçÑ¿ŠÖ‡"   ,
	L"MÃþ‡±Œ­ÚÓæÆâÉÄ¡Ä£Ä¤üN÷áÄ¦ôž˜íÄ¥¼UÖƒÖ„”Vðx‡¶Ä¢órÄ§„¯ð‘Ä¨‘½üOÄ©„¹ˆ\Š‹\š{éâÄ­ÜÔÄ°Ž”•b–£°t±u±‹³]ï÷ÇeÄª±‰»Š½QÑJÍˆØ{†ù‰sÄ¯Ä®Ýëõöã€Ä«‹º•½ñ¢²a²hïÒôŽüa¿}Ä¬õøËÏ_æŸ jò‡µcÀg"   ,
	L"MñòißèÄ²Ù°„Àc›£íøÄ±ãwÖ\öÊøœüEÄ³Ä¸ë¤ª…šÒÄ¶ÄµÄ·Ä´\ ¸®r®yÃk®€®³c®ŽãaÛ[Ä¾ØïÄ¿„Lãå ñÛéžÑÄÁÜÙš»Ç€Í]îâÄ¼Èrë‚Ä¹Ä»Ž¿‘H—úÄÀãfÄ½ÄºÅëŽÄÂíJ”æC—ÒäÅ"   ,
	L"N‘¹’jÞÖ¶gÇ_ÑD†ˆšÃ†Hƒ¹ƒºÂYÂxTÞÃ‹©Ú™ÂžÆ›²›ïŽu~Œ³¸oÑA›éSðž…Ø¿˜Ò’‚ÄÃÕyïÕæ“pÄÄë~ÄÚÄÇ…ÈŠ{ÄÉëÇÄÈñÄÄÆ¼{ÐœÞà¸™ØvÜ˜Øy†òÉiì„ô›ÄGŸÃŒYÄËÄÌÜµÄÊ¯GŠ…iÞ•‚™á‹èÄÎèÍÄÍÝÁœ‡Ø¾Ñ”"   ,
	L"NÎ—åràïÄÐ’o––‚OÄÏŠÉ®~Ç~ÄÑà«ßa•¨éªŸ²ÖQëyôö“Dœ¯Èlëîòï‘Ú‹Ràìe‡°ÄÒôTâÎ™òð–“îêÙß­ž²ƒ²ýQØ«™`ßÎFÄÓpíÐîóâ®òÍÔi´LŽH‰ëçtŽj«LÛñÄÕ˜ÄÔ…DÃ—ˆßÀ‹šè§ÄX´ZÄÖ‹CÄ×émô[Ú«ÄÅ±„ÔGÄØ"   ,
	L"NÄÙÄFðHõƒõšßŸˆÄÛÄÜÇ‚â…äG†«ÄÝÄáÛèâõÄà»uÄßŒÉ¶và\îêˆÐŠöœNâ¥Íe—´ÛCâ‰ÎUÓrØƒÄÞöòöFûŒýuÅMÃÙ£ÄãÄâ’v ùÆs–«ì»•ñDƒ“ëW”MËo™èXšîÞ‹êÇÃfÄæÄä¯[±zˆÓ©‹¤îÄçíþÄå•¿¿QÄ‹òÄéÄê¶j†P"   ,
	L"N¶|öÓõRöóùDð¤öTÄíéý“ÓÄìÄëÝ‚ºv”fÜT…`Ø¥ÄîŠ¨ÛþÄï‹ÝÄðá|á„ÄñÜàôÁ‹–ÑUÊ\‹ØÑ™æÕÄòëåÄó“IŽ‹ˆ[Æ}–¨ÚíÄùÄôô«Äö¶êŸ”¤à¿ÔÛW“µÛfÛhÄ÷ÄøŽLºQÅYåRò¨õææ‡êEŒZÄõ™Ç»HÞÁýmŽq¼b¼fÐA‡Ü×‘Übè‡"   ,
	L"NïDÃ€‡áÄú’ŒÄþßÌÅ¡ÄüÄûñ÷Œ|Œ‚Œ‰ŒŽƒ‘Äý‡“‹Þ”QªŸËf™ŽÂœè_ôVûH™F²…Øú‚AÅ¢å¸Œ„Ãôæ¤Å£ «âîÅ¤›\áðÅ¦–ƒžÈÅ¥¼~âoìÅ©Ù¯ßæÅ¨Å§¶ŒÞrƒzÞs‡‘âÊ¶ZÄ“·vÒaáx™×ÀYÅª’˜’°°JýPÁ…×a†Ž˜‰ññæe"   ,
	L"Nç×kÅ«æÛæå¹@ñwÂÅ¬åó³eæÀÅ­‚Õ“xÅ®îÏ»sâSÐZí¤–Hô¬Å±Å°¯‘ŠfœqÅ¯Ÿð`³–üQ \àGÅ²—jÙÐ“ƒ®™DÅµßö’ýßSÞùï»˜`·LÖZ¼KÅ³‘Â¼X·zÅ´í¥Äè"   ,
	L"O…Ë“¸àÞÅ¶¹p‰ñjíMÚ©Å·Å¹ê±Å¸‰pšWŸà®TÄpøk™¯Ëšæ–út…¾Å»Å¼ÄUñîÊqÅºâæÅ½‘Ya"   ,
	L"PîÙâZÚ•ÁTªWÎŒÑ—é›œ° ¥—”Ïæ^„ƒÒJè˜ÐˆãEõU¬i½l¯n¬aßJÛMÎ“æq»z–Š¯w±Ù·K¹ví@ªpÈqÞÕÌ¾œÞqóTÊEïRûË‘Ö€·…òŠóQ“¿šñ³W­pãu´B´‘ éÆt­”—Kœ_œ”ªtñF‡¥ómÍoªŽùL…ÄÇ[âbà^Æž»OÄ‡Ú“áÝÐv‰âñT"   ,
	L"P“žˆ¡ŠvŒ ØfŽˆÒLÒi¸¬Í—¶â·•”hÃ‡žTŒ´±~Ú¢Ò”ŒÛŠr°qÅ¿ÅuÅ¾ÝâèËÅÀ°ÒÅÃóáŽÅÁÅÂÐ’ÅÄÙ½ÅÇÅÅªT—“ÅÆ¹uÝ‡º’ ÛßßÅÉÅÈÝåæW´s±e®‰ÅËÅÊãÝ–®ÅÌÛA‹ŠŽ´Ég“„˜„ÅÍ¿Tõçžbó´Û˜æoíQˆmƒëÅÐ›cãúžÎ"   ,
	L"PÅÑ žÅÎÅÏñÈÔjœãîGäƒùbñáè‹ÅÒ›P›`ÃTÃpë„äèÄtìQ…€ÅÓåÌÅÔÅ}‹˜ºUó¦÷›ý‰ý‹ö„ÐI†çÅÕÓIóožÐÅÖÅ×’ëãÅÙÅØˆƒâÒáóÅÚžä ÅÛÞËÍdÝNìŽÑŒûƒÅÜŠEÅÝðå°’³hÈaüBµPµ^ÅÞCÃS–ÈÅßÐ[õ¬êkÅãêŠÅàšÅÅâ"   ,
	L"PïÂÅáÑpÙräž‚_¬ÅæÅåàúŠ³”äì·›Ö«˜Åä¸ŸÉ„àÎñ]ïö¬Þ\Åç‡Šåš\­›ÅèäÔÈ†…ÜÁÂM†Ï„úâñÅê›€yÃgÅé—ZÅë³yÝJéopàØñs´yÆMÅó’²¸†‚‡ÇlÜ¡‹ÅíÅï—Ä‚õ‰X‰k“smÅð·@ÅîÅô˜¨˜ÕŸÔ‘uÅìÝ~ÅñÅòåAíŠ"   ,
	L"Pó—Ïeó²óŸÀeíŽùiòuôJèmÅõœA°v„™’ü—ÕÅöÛs›¹Ž‡êCn†ÔØ§¶ÉÅúç¢ÚüÅ÷WÅû’yžÌ ò øÅø¶u¶y¼„îë”èÁ‘Â\Øwâtâ”ãYãÅü´iñyó‹àèäšåCõB‘šµFµGêVÅùÆ¤êoÜÅBèÁš·ÃYÅþš³Æ£¸“ò·Û¯ÚðÆ¡ÛýšÍn"   ,
	L"PØu—ÀŸÅýÆ¢ÄM˜[÷‰î¼ÄmòçëRô“‰ªõQºfÏKõùº”Á`ùd–CÜ±ÐKÆ¥âÏØòÛÜÆkÃ˜Æ¦ã›Õ|øaß¨‡ñ±‡ºÆ¨äÄœk“FæÇ‹œ²Dî¢‡Æ§Ýê¶¯@Æ©úûGÆ¬‡æÆ«‹xêúÆªôæú@æéëÝÄA—è˜FÙXÕ—ójõäñ‰òNÒÚÒÙGÕ›Æ­ôò]ò_"   ,
	L"PØâ®Æ¯çÎÆ®´‚”ô¿~ÂHóª ÜïgïhôwÆ°ËiêQéèî©ºgáo°Žî’Æ±ƒG„ÜàÑæÎÒ‘Gë­Æ²“Å•ÈÆ³Ø¯ÜÖçv‹±æ°Æ´µI·|ñPóD«nÆ¶Øš¬VæÉÆµîl‹åËd‡¹²‹ò­ïAÆ·é¯–Wêòšýæ³Æ¸Æ¹®jÙ·›Ú³fÆE¸zîZÆ½ÆÀÆ¾…çÆºJÆ»àZ"   ,
	L"PÆÁŽ—èÒ›¯«rÇLŠÐÆ¿ŒÎŽ£œKÆ¼Íg‰BŽ±Ÿv®JÀÂ†É‘ÍƒÔuÝZöÒ„R‘k¹’Ýƒ‘{õG™qºqÌOîÇÆÂŒûÆÃŠËá•ÆÄœÂáNŠáwçkÆÅ‡MÊXÛ¶ð«Öc™ØÏŒžîÞóÍãOñpgFÆÈ”’•^›¨çê†\ŸBÆÆ³kÆÉÉbîHÆÇÆÊïH’g’h’½ÞåÙö¹r"   ,
	L"P…ð†VŠç ÁƒÍ†RÆÍê·ÆË’pžÊŽ}Ž~–¿ê†¯jÆÌñmàÛ“ää“òõ‹ˆOÙéÆÎÆÐÇŽÆÏÉhÆÑƒWáT‰è±å§²r·oïäÙŸÀbçhÆÓÆÔÆÒÆÖŸMÆÕ‡þäß•®Æ×ª˜ãë«ÖE™kïè×Võëç’ÅmÅnÆØ"   ,
	L"Q“³´x•üû]úIüÔˆÜ•ƒ¡™ÂÚmÑE„“”¦ØÎáëB³MÃIã^’M¬g²•ûXý”šðÃQñU’uîM´ëaœ‚Åpà ”Œ”ª¶š©¾ƒÓs¶Sàœçˆð‡ŸdÛeÜeÏlœgÈWúñÊ†kÃƒrìy÷œöúYè~“BÈ“u“°™„ßŸ}Ÿ÷äÐœ©Ïf×Ká½þ‰‡„—¸¯C‚Œ‚Í"   ,
	L"Q‹}Í„˜Hõ^ÇMˆ²û…‰ƒ‘[šVä›Üù‚’ºôòÚ õLÛRÚzlöÄèL’ÔƒÍX‚àùŠÜjûŠûŽŸa¹„é_šKšMš£“U’®³³LÕF…•ŸÈ RÅˆøBšªÆßÞ€ÆãÆÞÆâ‚ˆÆàÆÜèçÀŽàVŠÝ¢ÆÝ’Ý—RœDÝÂ–OÆÚÆÛ¼–Ñzƒ[àÒ‘i˜éÊÆá¾e‘h´mÕƒ"   ,
	L"Që’õèôtçKù†ØÁÆîÆëÛßáªŒóÜÎÆäÆæ”ÅÆçÆíÃX¯O¸g„~”Æ”çêÈÆêÍTÍ[ñýˆÎÆéŽ©’åä¿œjªXÆèÝ½Ú–Ü™âHæëÆï—ŽÆåçùç÷ì÷òÓæ³ž´JÑwí ônôoÆì»ž¾Lôë¾N¾zÎBòà­D¶QÞ­ÛaÏB÷’‘¼ùËs™‡™–º“ÄšòTòU÷¢ÌIõš"   ,
	L"Qùuù}÷è»KÀdÅ Ï“ôGò€ôyö’«Oû˜ÆòßŒÆóá¨ÆñÜ»Æô…Ñè½«^°ž†uØMÆð†™†š†¢Šíç²•’—¤ôìÖHº‘êMÆøÆýšÝãàÆùÆúÆû³HÆZ…æÆüžÅ±[…ýÆõÆöÜù–ÖÓ™†ƒ™û‰óÔ—‰œŒœÝÝíÓ“ •´®P´\‡r‘sÆ÷í¬´w´ƒËjµJÀ™Ï„Æþ"   ,
	L"QÝÖ’‰ÚžáMì—ˆXƒîŽ˜Ç¡Ç¢š³sÙ÷ÄÇ§ÇªÚäŠdÇ¤šþÜ·Ç¨ÙÝá©–e›FÇ@¸dÇ¥’ŠÇ£»xã¥ÍOØ@Ç¦Šú ¿âTÇ«ëeƒLí©Ç©å¹ûeåº“¾“Ã¹ˆÕßwå½îv™Œ”o”p™¥ºžçcùk”qòqèBôRôS»`ía¤Œòø’R’ƒqÇ°îÔškò¯Ç®Ç¯Ç¬"   ,
	L"Q‚¡Þç“bÜ‹`âjãQ‰‰˜póéäEÇ±™NåXÇ­æZübòcžKò`ž»Rö‘Ç³ëÉœ\Òã»Ç²ÎS“Ç´ç×À`×lècÇ·„XÜÍÜçÙ»ŒÇµ‚ßÇ¶—èý°|É`‰qÇ¸ÊgƒŽ˜ ºGÝ€ºR‰µ‹ì¿yÇºÇ¼ãÞê¨”ÖÇ¹«oª]¬jõÄ†ó—¾ª}Ç»†ÜœÙòÞïºè‘ê˜Œ"   ,
	L"Q ›¬šÁzïÏº[äÛ„ïêÛ–æjçIçjŠÇ¿Ç½æÍÇ¾éÉ\Ê@‰¦‹Ô™{ ÖmÅšÌbÇÀôÇ“ŒÁu‰‚“¬¿‹ñßÀHìÁ†…ŸÍÁ†ƒ¿­™ÇÄíÍàbàzÏõÎàƒà…ØäÇÃÛ^ÇÂ‰Œ´`îN‰§ŽÉÇÁçØ´“å æ@¿”Ú‰ÜEÜFÇÇÇÈÇJÜñÇÅ³~†ÌƒS˜“ÚÛ‡a‹´ã¾"   ,
	L"QÊw÷³éÔ˜ò Ö¯ ÇÆ´™Ë–×SÚˆçyíXî˜ÇÉá ã¸ó~ÇÎÚ½ê~ÇÍŽÇÏš¤ÇÌÕVó|ƒsÇËÇÊ¸[ÂNÜNÇÐÆj°mÇÑÂÇÒ…‚æªÇÓ…LÇÔ‚ž‰êü›­ã«›ù¸›ÜÍ‰–Aóæ¾fïÆôŠºDÛo·lË~å›ö@çƒ¸`»]Ç×ÇÖÇÕôÀóVÈB‹]ÂÕWôÓHîzñŸ"   ,
	L"QõŒ˜ŽÜÜËÇÛˆ¨«²›ÇØÂlÇ›ÍZ’ÍÇÙ¬lÇÝâsëdÇÚàºäÚì€àßÇÜ”ÜøV‘¦éÕà¯òû‘¥Ïˆˆa•T¸—vÚcŒ€ï·ÇÞŒ‹äuÏO…ÂßÄ’aÇß†wÇ™Þì“l“åžpÌCìiÇàÇâÇáÇãÇäàWàõšäœ[ÇåƒAFòßÝpöëè[‰ð®_„…„ÍÇéš„³|Çç—³"   ,
	L"QÇèÈ•¦“÷˜½ÇæéÑ÷ôÜÜÇêÇëŽöí•NÕˆ™”ö¥Çìƒõ’á³ óäìm‘cíàƒ žDóÀ™¼Œ^õ¼öÆ…oÚöÇîñ·Üä–÷¹HóÌÚ^ÄŸwŸzÇíÅ|òËÍ‹Ÿ¦ŸÅ±ž²`¸Fƒ’‘w™K­WË}¸\Ë•ÇðHÇñˆwnÇï¶kŒxòÇ‹pÈcé±ûjºE¾Î~·hÚ‚öúÏbíF"   ,
	L"QíGÌUöpöqù”ý•…´Çô’@áì«U–_ÃFÇóò°ÇöÍAÙ´ÓaÓˆÓ‰Çõ†p›½¼zÇiÞåÏá–—Wš‚šÂÇòêäâU¦ÛÏœª°“±HåÙŸª½‡ÍôÃŽ€ÓpÙg­GòøäMábõF÷üõ‰ùjÐ@÷A“zôÜÇøÇúÒ…Já«Ú°êrÇýˆoÇüE’|›µìîÃlÐ …^ÇùÇû¹L»–"   ,
	L"QòÐÔxÇ÷çñl‘t”·ÕoñnüLó”Ú…üDÜ|ôð÷ñòŒö÷OÚÛ¾”×ëÔÇ†Ðdð¶œTÇþ½PÈÝ@Þ¡­SíáÏJøzè³ÂJÏgüšÞ¾…Zßž›‘ó™áë¬»cÅJñ³ÐRáéÜdó½èŠûYÈ¡¸lÈ¢¼ Ôs¸yÈ£ýx…È¥„`…íÞ‘àTÂ^ãÖêïÈ¤é‰üCé˜ÓNÓUüzÓY"   ,
	L"QZãªÈ¦‡ü—¨ñògçzÈ«È¨çÚ¹ŠºÈª›§ÜõÈ­ »éú†­ˆ»Š÷³È¬³oîýœ² ÅóÜ½hÄCÈ›“‘˜T¬†ÓjÔÝbòéãŒ˜ØÛm¿XÈ©êB÷™÷ÜŒAŽköe™àýjÐSÈ§ïEÈ®›Lî°žïç¹¾JÌ†È°È¯Ž† º—Ñ„áíj„ñÈ²È±ÉUÈ³È´ˆ«‚í¨È¸³‚È·"   ,
	L"Qã×‰U“n°”ãÚÈµâÈ¶‰”‘Uš¨´_Ú| Pé µCêIùoµ]‰æ‡ïnåÒŒlŽ È¹ÁtÈºÑdÛ§"   ,
	L"R…Êƒµƒ¶Ÿß…mˆc¿ó’âc–¹ÏuÄž’fƒÈ›ÝÛœ‹úÇŒÇy«A™“Û’Á@‡Ý…ßÃVÐ€Ð…ÍcÐ™òÅÈ»ó†‡Y÷×È¼¿‘ƒÑÈ½Š˜ÜÛÈ¾«z‹vÉG·yž«KìüÈ¿ð¦Ü`ôX‰´ÈÂÈÀÈÁ }ÈÃ‘Ó×j×ŒÜéÈÄèã˜ïÒYðˆ áÈÅæ¬ëN”_ÈÆßvÀ@ÈÇÈÈŸá"   ,
	L"RÈËÈÊÈÉá–Zä¶eÆ\âmôã…øžÈÌÜó–ß–áÇY¶‰ïþ¾BÜrÈÐ„UÈÏØð¡×šÈÎŒã’PÈÒÈÑ–k ®ÀÃMéíÈÍâ¿Šž¼xñÅ¼ŒÓ•Ü—eÑG½VÄHìzì~ígïƒÕJïšÈÓÈÔÞwµiÆeê—ÈÕóR‡ðâJâ~ñ_ÈÖëÀ–ÑáõÈÞÆŽÈ×ÈÙÈÝtš¿ŸV‹†áÉ"   ,
	L"R½qÁs‹’“m“r“–˜xÈÜÈØéÅ˜sÈÛ¬Œ·ZòîÑ’éFšÕ¿^ÈÚÎñŒó“‹æŽV hægžq•íÏ”ÈßŒ]‚ÔÝP·\…œ¶bÈá»€‹YÈàœnÈ|¬yÄ\ôÛÎjõåÝŠåˆ÷·­~òkökù’˜QŸ§íqÈâŒ`Ž]ßÈçûŽšÈã–ôÑMï¨œx¹TÉSãœÊ‡Èåønàé‹çÈæå¦Þ¸"   ,
	L"Rø›•ã ^ñàÈäò¬á}îž÷pÈêÃNÈéÈèàrÈë’CÞz–dä²†ä‹‡äáçÈÝêøMÈì¿d”Jˆë“É‰¼ÈîëÃÈíÂX‚¢Ü›‹\Þ¬}ÄQ‹¯´M¾ÎpÝ‰­wµO—M®c¾qÞ¨ÈïÊt™GÀBÌGÌHÜÇèÄò¸ÈñÈðî£…±‰ÇÈòÈóécét™˜ô…ªÈôÙ¼Èõàe‹SœcŸx—í"   ,
	L"R×ÉmóèºO kö}ö”úU"   ,
	L"SãGìáè¼”c‚ÆÀu…¢…£…¤†Ð‚ð·_‘¨à“’‘¸ž»æ\Ñ–„x“½”v“˜î‰jˆö¾D\Š¿³×ï†ˆÃá~”™ªkwÝ¿W—Œ˜BY‘mÀŠ¿\æp…g†Î“ú·ƒdŒpå~ßfßr’¡ê^êAêyÌt—­Ø­íH†Fçií}éXì[ç™ÒŽ¥Ç‹‘ˆû”ƒ¯ŸÊ”ž{šÑ·DÐL"   ,
	L"SŠÌœV’öôˆTˆUÛÉZËNèAímíI‹Žš —ªÝØ’µØí—EÈöÈ÷ÔQìƒ¥Ø¦ìªëÛÈø“—ëMñ`ïSË_™¨–Óšºà“HÈûšËÈù‡TàçÈúî|†ðÈüƒwÙº›ÌƒÈýqÈþë§šÉ…xšÐ ÑôL‰ÐÉ¡‚ãÉ¢ôÖ¼BâÌ™V¼R¼V¼W¿™çDð€‚^éd–øÉ£˜šÉ¤Þú"   ,
	L"SíßÑ˜òªærî‹É¥†Ê’ûýÉ¦œÐÉ§çÒëýöþïbòXö…÷fÉ¨’ßÉ©Ü£ðþš×²„óÉ«–ÜÉ¬ØÄœiï¤šm¬X†ÝÉªšoäC®‘­“öæí¯™ð£­­iži·wÀN·†ÞQçmÖ ïoÑSÂ{É­˜¦ÒIÉ®ôOé~¿LÉ±É³É´oÉ°†~’­ªQ»}¼†É¯ï¡ðð³ÊeôÄ"   ,
	L"S˜×ô‹öèéŒæ|õõÀ\Éµƒƒ¿‚ßþÉ¶Ž¨ÈS†Ãì¦É·ÁœÁ é„ö®É¸ºYºkºÉ¹•ñÉ½áêßˆZÉ¾„hÉ¼–uÜÏæ©ÉÀîÌÛïªGÉºô®¯ZÃˆÜ‘¸–é^õÇ„š“‡AŽ»É¿Ê`äú¿•Ü™cëþõŠÁÁƒÉÁÉÂžèê„éW•Ÿš±˜ŸÄÓ@Ú¨ÉÇðÞÉ»ÉÈÓ˜"   ,
	L"SÚ]‚ÞÉÆ—ÖãˆæóƒRÛ·‰‰ŽÉÉæÓÉÃ”»˜èÉÅ´ŠÖbÉÄ¿˜óµ×iÙ ç—ðƒò~÷­ž¨÷XÉËéäÉÌõü‚ûÉÊ‘^CÊKš‘ìØÏDÓxÖ…ôlÉÑÛð‘ûÉÎÉÍÙpèlAÉÏ Œ¬ÉÐvç´¾y„ÉÓÉÒÉÕŸ†ÉÔ”ïóâô¹òÙÝiÊ–Ÿýó™õ}É×ÉÖ–¶«xÉØÉÙÛ¿"   ,
	L"S…pÉÛÉÜÉÚŠ¾ÐŒ½B¾KäûÉÝâ¦ÉÞî´ÝfÙdÙh™ÉàÙÜÉßÍ…Éá’ÎØÇÉèÉçÅh…‡ÉäÉæ›õœhÔOÉâÉåÉãäÜ‘b“ºÊJÏ‡ísòM‘Øž—÷ê™ÝÉêŒæ’JÉìÉíêÉëŠ»pÉðÁAÚ·–¸šá«|·Œ»rÉïv®`±mÉéˆÞÉî¼ƒÂ—ØÈÑ[ÔYÁKÉ†Ô–"   ,
	L"S®eÊQŸöËMñ‘÷“õ˜ù_öYöŸÉñ˜Yãhö•ß•z’bÉòÉó² ßÓïòŒqÚÅ×ŸÉôäÉÔBŒÕ”îTô•Ö²s‹ðžcÓ\×}Éö‚L•YÉõëÏ›Ø±sÉøµŠÃŒÄIõÉ÷é©¯}ò×Bäv¯”ÉýÉúêj…ÖÉù”Î•N–™›ˆÆš}Éü«{¸iÊ¤ê…•úê’óÏœ¤Ÿ„ÉûãHÂ•"   ,
	L"Så•ü›ù|Éþ‘™Æ×WÊ¡íò‚¯œƒÊ¥êÉ•…„Ê¢Ê£„ÙÙKáÓÂ}‰˜˜|Êo™TÙ‹Ê¬Ê§Ê¦…ÚÊ­Ê«ßŸû\ŒÆÊ©›¸Ê¨ŽŸ½Jœ¢ÊªÈžœÛœáª{ÉNÝéÔŠ¬‹õ§øOÎtø[Ñ öõåœöXö‰úPÒ|»iá‡Ê®â»Ê²Ê¯ÞyÛÊ±¸bÊ¶ÊµŒg•Eïz]Ê°ìÂµuÊ´"   ,
	L"SÊ³Ûõ•rÝªŒœ›ßY‰PÖœÒÉP˜tÎgãvºIöåõZüœüöˆÊ·Ê¸dõ¹Ê¹Ê¼Ê»ƒ½Êº¹E˜Vâñ‚Ê¿ÊÏìêÊÀFÊËÊÐÊ¾…bÊ½…«ÊÂÊÌÊÆ…á–ÉÊÓÊÔÊÎƒàÊÒ^ÊÑÊÃÊÇ–§ÊÁ±cêÛÊÊ–òžø±i±xóÂéøÊÅîæÒ•á‹«ß±“JÚÖÙBÊÍ„ÝÊÈ"   ,
	L"SsŸ³±óßÓlÔ‡ÝYâ‹ï—ÅkÊÄŠ]ÊÉ‹ÒÌÕœÕžß}ðSó§ºº Ònö|ƒ¾­—…§ÊÕÊÖÊØˆ–Ê×ô¼ÊÙÊÜá÷ÊÞÊÛÊÚç·¯lÄf‰ÛÊÝ¾R‰Þª•«FæÊéì¯Êãç£Êå–€Êàêxæ­–µÙ¿‚‚•øÊâ¼‚’æÊáÊçŸYÝÄÜ“àg¯EÊèÊæÞóë¨šÌ½ˆÊäÛSÛ\"   ,
	L"S˜ÐÊßÝ”™]õ_”dž‚ùeŒ«ïøŠìÊëÊêÛÓÊì­qÚH•¤ÊîÊòÊðÊóü“Êñ©ÊíÊï°PÒe¼^Òl»PÐO÷n÷t–XÊõÊùÊøãðÊö‚JXÊ÷ÊúÇOË¡ÊüŽõ½RÉDÐgÑVÊý¸wëòÊûÊþ”µäøØQ˜äòåfçTùŽÌ Ë¢à§Ë£ÕXË¥Ë¤Ë¦Ë§Ž›ó°…iãÅË©"   ,
	L"SéVË¨äÌÄYË«œöËªëpæ×óZ‹þò‚™Üµdú{ûtÆCóLûUË¬‰u‘S˜¾¿Yç`ž“Ë­ÃŸÕlãßË®šìéjŽœ›ä›çµˆË°ÑcË¯Ë±˜JË³Ë´í˜ÊŠ˜ù²i²pË²ôBËµåùË¸Ë·îåšFË¶²àÊÞ÷ÝôËÔéÃ´TælÛÌË¿Ë¾¼iË½ßÐ›q‚hË¼lð¸‹wË¹½zçÁ"   ,
	L"SòÏ—ö¶Dãjït„@ØË˜{¶LÁQäFïÈË»‡zPËºäù¾ŒÊ‘Î‡æJÏaÏzï\òlçrúƒýDËÀËÈËÄÀŸËÂãáËÅËÆËÙîæ¦›…ìëýŒKãôËÇæáÙ¹ŠÙ–Æ µ—t›—›åÃBï~óÓñêâL¸rÒ–ËÃËÁØ|â–ï•¶Tñ†ÊœƒòIž[ÏArâìËÉ–…–œŠ»–·‚‘"   ,
	L"SÚ¡—sáÂŽôäÁÝ¿áÔ³—Î@‘¡™€ëó ËËã¤’¿ËÊñµ‚öèØ‘ZÂ–ñžËÏËÎËÐËÍËÌÔAížÕbðmæƒð’Èànà²ŽùCËÑäÑªvÉLÉrâÈì¬“¡ïËËÒòôágæ}ðtï`òpÛÅ‚ÏàÕî¤ËÓÞ´”\Ë’™¸¯˜ËÕ®dËÖöÕ¸@·dõ‡ÌKÌV™Å‡ÕË×«TÙíËß"   ,
	L"S›ƒËà›«ä³«ŽËØËÙšƒ»óX‚ÑËÚÔVÚÕà¼‰OËÜ‹•ãºËÝœßÃCßiûhËÛå˜jÄhÝøö¢Úxßp‘ˆ˜Â˜Éšä_ðM¿i­XóùË‚ÖqÛ‘ò“÷Tú‰â¡¯iËá…Wµ{¸Œ¹gËâËã‰åÆVËä‚‹†a›ÔÝ´Ç]íõÈšœñî¡ŸÕå¡ìšëmËçËåËæßU½—ëS­…ÄŽžv"   ,
	L"SólËè‚Ëê³ZËî»‚ÚÇˆ¼ÀÃœËìšqšrŸ«ËéËí‹ÓÜ·[ÕrÙw™pìÝ­j¶XËë·u¿…Ò`åä”ø¿“ÀZçw×\ç›ËïáøÝ¥â¸“qªsÉpïŠ˜ƒÊ˜ËV®pËðËñöÀ“pé¾¹æ{Ž…–Ëôæ¶Çj‚éêýèøËóíüàÂôÈËò“™ËõÚtºwºz¿sóšõ€ËùßïË÷Ëö"   ,
	L"S¬R»Ëø†î•­œÅ¬æaæiææ•ßCœàÎRÏÃâàÝ·ñâÕ¤Êô"   ,
	L"TÖO†žÑgƒ{¶UÏsÀWé‹²_èK«ž‚Dk ‚¾I»I‚mˆÇÉ”ù‡â‘“ÒÞ…Þ‡í³ÇEßQœÍß_æ]í^ß¾ÍfÜ–ÙJ°D“Û‡d—ðZüh”†™éßTÊŽº‚ÌoêW–]ìâ cƒ\ŠDóƒÔgwÆl‹XÖBîŒîâšµ÷É‰†—ÂÚgŠcâ‰’dœ§Ô˜î×äWÑƒÎP˜ú¶ÚŽÝ‘‡"   ,
	L"TŸõÜ€ä~ì‘òo…õhŒ_ËýØçŸüÝ‰‘Ödð‡p”U”Á¹åŸŠUÃã@›IÏ€÷WÕgÜæÈVŠ¸çÊÑ|ÞÐ›ì¬Ÿƒ©¶´fäl–ŸËûËü ­µk…úõÁîèËú˜däâÑÜD‚@Ëþ‰‡Ì¡õ]÷£«HöÌ¢ªHãË„›ø“‚ßeåÝê`é½šÏ¶N“éßÕwÌ¤‡–åJ‡Å"   ,
	L"TêÌ£ìŸêFíOêY×nÜcÒk‡òŒLææÌ¥Ì¨Û¢ˆrÌ§Ì¦ìÆžåõÌöØ¹xÅ_ïUƒˆõT‹ê”EÞ·™…»FÌ«ƒè‰ûöÌ­Ì¬ëÄîÑÌ©»†ÅvÌªâœÌ‘B MÌ®Ì°Z†®¯aÅjØÌ¯Ì²‡c Ì±”Z”‚ž©°cÌ³ê¼‚„Ì¸Û°Šò´Žñû˜WÌµïÄÌ·‰›‰ ‘…Ì¶"   ,
	L"TÕ„á]‰¯•ÒÌ´îtÀ—Ë“‰Â×TØáv×ZÀú‚ìþÌ¹Ì»îãÈIÌºãg†ú‘˜‘Ÿ•Æáa­fÌ¾Ì¿ˆÅÌ½‚èœžƒN‡@Ì¼ÅlšUÙyÌÀï¦‡R„¨ôÊÎvËTïÛÛçMç|íUü‘â¼ˆnÌÆÌÃ‚Ú†°ÌÄàoÌÁÉÌÂäçÉyëG˜yfŸ¶è©¶KÄgéÌ´g¼CÌÅ˜üºLÌÇó¥"   ,
	L"TÛ}¼Qó«ÚZõ±æhðnêOðyúSàûÌÈ‚«ÌÊÙÎñíÌÉéEæ†ƒ¯‘Ü•ò ‡²˜è’ÌÌ“­ÌË C—‰ú|ÌÎÌÐÌÍ½dÔ|‹—Žµþ“†ÌÏ˜…¬•èºï‘¿_¿lýÖzíNíw÷ÒÞ†Gä¬ÌÓÌÒÌÕßû—ƒÌÔÀ‡ÌÑµŽÑi¾TÎIìŠá[ì’ä•åcñŠ™„òPØ»ÌÖÌ×Ó‘®z"   ,
	L"Tìýß¯ÌØØ–ÃŽï«í«äˆÏcÄ†ü’ÌÛ¯\Ž¸ÌÚÌÜbëøß‚¿gÎŸñÖ`ƒ£ÌÙòv»LöŒ»TÌ„óIìL†z–YÌÞÌÝÌàÌßäRúeúf…†ç°‚¨«ŸÌä¨ÉÌáœv¶”ç¾ÁHßXðÃ†Ù¬v½´YÓz¾ŸÊƒÎyÌâÚ„Ìãõ®ÖpÛ‡å÷–î}õ{ùYòfö[ù•ù—Ìå’«"   ,
	L"TÜnóeÜƒów‘øÌëÌê›¢ÙÃã©ÌéåÑŠÌè’óßPµ“WÌæ˜NñÓÑ{šóÌçó›­ƒóž»GÌìƒÌŠõÌíáLìjüVìpÌïŒÄ›pÌñî±®xÃb®ƒ®\ÌðÈJœÌî“ãÙ´[¾g´k¸Kø‰­kêDúcúlãÃéå‚†Š¤’×œL•‹¬_ÌóÓ`¯t±™Ìòï›ÓCÙqå`ìtÞÝ"   ,
	L"T¬™²VÅq”þÙ¬ŽçÌôìöÂwÆKÌõŒýGÌöµx—lóÔÉ‚ö¶˜Ôòèäpì›÷ØöæÏCõæxýföœŒi•q–IÃxñ»ÕA¸I‹àÌ÷ôÐ½rÒ›ÚqÌøî\¼gÌùÝÆÙNÌúÍuƒcø‡ç“èFò…ãÌûï”÷ÑÌüŽØÍ¡ÆJÌýÂ[…ˆÌþŸN½–ì˜Â—ÂŸaÂ dß‹Í¢Í¤Í¥Üð"   ,
	L"TÍ£æÃµœs¹jÝãòÑ—þ˜wéƒöªÂŠÎbÖFüžˆN‚KŠÇÍ¦›àèèŸP¬EÃ‰Í§ïFÕPäbîcìh‡ìžçÍ¨¯]àÌÉŒ˜¿Ÿ×ÙÚÍ¬Ù¡Í®MŽä†LªIÜí•zÍ©›ÏžúíÅÍU±¶‚Í­Í¯»½pÐhÍªãPÙ×„çã~ï ÷‹äü•Ó–S™HšÔ ÕÄ€Í«õjÍ³Í±Í°Í²"   ,
	L"T½y½ŠâúÍ´‘Q‘qÍµ‚ÊæBÍ·Í¶÷»î^Š‡¼}”«”ÓüWÌeÍ¸Í¹¶dÍºLÍ»†l›Þ’Øˆàœ£¯fÈ‹áäŒùWýC‡íÍ¼ƒòxŽêÍ½’¼Í¿Ý±Í¾ÍÀ—^“\¶•‰TÄ¯…¹\Ä]É\âŠˆDˆEOÛTõ©ñGå„òBùIùúhú“ÍÁˆMÍÂ›BîÊâQƒ·ÞƒÍÃÇÜ¢ÝË"   ,
	L"TùrÍÄªlŸ™Ø‡ÍÅ‡âÞÒˆF‘_˜¤™ˆæ˜¼aúoú™ˆCî¶åèœ¨Ñ‰ÍÆÉ—Ë”ÍÇëPîjîkînôs·~ÌLÛ‚QÃ•ÍÈƒUÛƒóhÍËŠÑìÕÍÉÍÊòDÍÌ…×–NŸlêÕü`ÍÍÆXâ½ØZëàÜ”÷ƒôë˜ÍÎÄ™ÙÛ®™ˆdØ±×™ÍÐšúð˜ë…ï’„ÍÏ›k‚MÇhÐ›Óš›ñÃ“"   ,
	L"TÍÑï€ô…ÍÔÙ¢ÍÓÛçAãûÍÕèÞíÈ³aÐ†ÍÒ½Fˆ÷õÉõ¢´PñW˜’ñjÛ|ñ„ñ…éÒõDørü˜ònö¾ò™üƒÍ×š¼âÕ‹sÍÖ—ø‹µ™EùKÍØèØÍÙÚ—šÍóê»X"   ,
	L"UÞm°iÑCÎ_•éÂ‰ŸH HÜxÉIÉ…ÂS·E› šµš¶ÆŠ–þšÄ–GŸ‡ÍCùæç”Å†ìTê[ŸeŒËš`ÁåwË€ÚJ°›”ÉÂqµs"   ,
	L"WÚ~º‡f†„ê‚ýŠÈXévêKêPØž·˜Š¹i²z†JˆåãŽÄÄŠänÖœžx½Œ–M“ÖÉ^‡—”NëoÅŸ’H‡ˆ’[Žh´jËh˜´à„Ïˆé‰î…Ðíië‰ìW›^ëøs×OŽ’šzì…²yÏw‰ŠÃŒR’ç­ŽœrÎT’Ú¬]Ùï“ãözŒÜ„¾ÍÛÍÞºÍÚÍÝæ´®|·“‹z†åÍÜ“‰"   ,
	L"WœÎj¸Dü|”…ÍßØôßœ…÷­ ³[Íà†ìëðÄeÒmící€Íá†·¸áËÍâÍäØàŠþŽ¦‰GÍå±›òêŸÍã‰Ïž³Íè„\š÷æýÜ¹ÍêŒññ’eÍæ¸Š¼w’ÂÍçÍé¬TØ™îBßÍð‚{†nÍìÍí±Dˆ¾ÍñÍï•Š—içºëäÝÒ•–—µçþÍîîµÍë¾O¾UÝnÛläjå†"   ,
	L"WÍò…d…e–v’ÌÍóÈfÂDä[ËHåsÙ–æ~Ú@ŒµŒ¶Œ·ÍôÍö“ƒÇÍõ©´ÇwÍ^ÍøûÍù¸Í÷Øèã¯ÈD•™—ŸŸƒÍ‡éþ¾WÎ\ÕsÝyž_÷ÍÍýÍüÞ‚Íú±ZÍû–RÎ£ÍþžùÙËåÔêžÚñ†Ò‹W‹nÌ“G“fœwŸŠÈ–ÝÚÎ¢—Ü˜LœÕìÐÔ•¿JÎkÓAŽUÞ±÷˜"   ,
	L"W°IÎ¡ögöhàíÎªÎ¤Î§àøãíÎ¥ãÇ_e›”žéífÎ¦ä¶Î¨á¡Î©Î¬†Â‡úáÍŽ®œ‘œ¿ ‘ß`Î«É–àŒ‘¬žHå…éõd°LÓW àìSÎ°Î±Î²Î³ÆYÎ­Î¯ì¿çâä¢æ¸’Ë›¾ÇUÚÃ‚¥‚Î™—|³uÎ®Úóó[½@ÎÎâ«È”ÉJó\ó]•¥—ÛŸ˜¬|ðô"   ,
	L"WÄ^ôºè¸ƒ^´SÎOÎVöÛŒ¾•ÊlÕ†ÛcílîQƒ¤žSå—õn‰Ãítï]žw”ÍÎÀÎ´Î»Î¶Æ„Î·Î¸ê¦Î¾³}Ç‹Î½Î¹‹yÎ¼â¬Ÿ£‰ŠÎµÎ¿ŸÝ Ò´o¾“ÎoÐl‘£è­MÁWÐoÖ^ð]õKÏGÒEðjÎºË—ÞEçAìG÷ÌvðŠ×~ÜZ×ˆÜ^•j‰eÎÂšœØ¬˜v"   ,
	L"WÎÁØn÷—æ’ðwö€ö“ÎÄ¨ÎÆÆ[žÉ³RÎÅ¼yÍPÎÃ«œãÓâ†ö©¯‡Â„ñbô•øYøjÎéé”ÏRéšü•êZØØÎÇ…Øì’^…ÝÃWÎÉ—SÃ‚ÎÈ·g·€ÎÊŠpãëÇ|†–œbÃ“h“‹½ƒî‚è·ÎÌÎËûlÎŠæfúOŠT‰RÇœåÝî•²²\ÂÎÍÞ³®YÀšýNÎÎÙÁÎÐ"   ,
	L"WÝ«†›óœuªiÈnà¸ÎÑ¸CÎÏÎÛbÎÒŠðŠñ’Ó¥ÎÖë¿ÎÔÅP‚¬‹_á¢ÎÕä×ŸsíÒ—çÄOÎÓ²Yü­xö»ý}ÎÚÛØvÎÛÚùÎØ–gÎ×ÎÝ›´ÎÜÎÙÚ„·—âEàw†èÕGÕ_¹™ÎøŒæuöƒÎÞÎãÎâÎá…ÒÎßÎà›žä´Æ•Ç`¬@µûcŸoµŸòÚÊ­NùM"   ,
	L"Wõˆ÷ùú~WÎåÎçØõÎéÎëåüâÐâèâäåÃ•JÎä«bÎê‚W‚—Îæ†•ŠÕêõ« ‰]““ŸÊ´IðÄ¬Îè‹³T‘“Žåqƒ˜î®Wù^ÜRØ£ÎðÎñÎìÚã°Œä’NŒíè»ÜÌíÎï³J”–Îó„Õ’Îòš»|ßAÎîìÉæÄ¶ðíëFì}æðŠVÎœ×Îíå»Ÿ½Õ`ðÍöÈ"   ,
	L"W¸PëœýHìFýIÌFò\úF"   ,
	L"XšGŽß‰®’QŸL×¼YÅW™úœä‡båeKÕ™“©½oÍmÒŽŽQõqŽ`ôk…îÖ›Þ†Æ’œéšBàAÎ˜†ÛŸÀ _“Eé{é•é—ô\ãÖ—GÆSÓi‘¤Û¨ªB×ß€éIèGƒª×fŒ@ÈÞF’î“ôåæÊD¿]ÀMŠAˆ®›Ñ‚íÑW…­Ëöx—g¹a´šÒŠéf²vøŸÞBòœ½gÝ^œœ"   ,
	L"XîRÓn…ÃÀTˆlŽyˆgîy±rüŸýAäm½ª™›Q›‰„äàåŠ®žF÷ˆÉ‰AêR•všEšL¢“y‘¾‰·‡ZáœÇÌ_Ì`·SxÐiÇm¶[­ŒÙ‚“Ï×DãbãcŸœÖŽ‡I±P‡›j—«Ö[šâ™÷ÅO‘aÝ¡Á{Ên˜½‚]†éófŸò±½­‚É’÷Gõ@Ãa…sÅb´Fƒ¨„ðÌZ"   ,
	L"XÀvÀ]ž¢è•âlöwò}ëš¢˜fŠ™áŸ¿„ÇzïYŠ·ñŒj•g¹Gýa†Cã_ª“¹›ÎEŸù…®ËÞ´c’˜þŒOúZ™A“ÚðhðuŒÏšY±]ÉŠÚU¾–Û×í|’ÜÏ¦ÙâèÏ«Î÷Ò‚ÎüÏ£…kÎôÎöÎùñ¶ÃZÃ[‚`¹YÛ­ðœßñÞÉŠÖŒÊÏ¢•„šãä»ÎþªLÇb†ŒÏ¤"   ,
	L"XÏ§—Nì¤äÀœlÏ©ŸXŸ_¬NÎøÝ¾ÚTâR‚Ý¦Îú•‘ŸmÏ¬±–Ï¡ôÑôâÁ—ô¸àq…wÆÐÏªŸ›ðªÉYÎýÙÒ˜~Ï¨Îõ¾kòáØgðFÎû‡q‹ÄæÒ¯ŒÏ¥ðO„DéØ˜éì¨ìäŸçŸè¸OôËó£Î‰åa O ×²q´—ó¬ØGØHØlØ‰ÀGëvõ–ùTÓ}×@õµç^ë^ŽdêØ"   ,
	L"X x Þá@Ó‚÷ûÐPú Ó„è„Ï°àEÏ¯Á•Ï®êêÏ±—áÉjÉtídÒ Úv˜›Î€Ë@ÚôÏ­ÖæˆìI÷žïeòwò„Òu÷@óN– Ï´çôáãÏ³Ï²È}Ýßâ|åïSÝûãŠ‘‚‘ƒ•Ê™SìûÖL‰¸¿uÖlÏkÛ’­t÷^²—À{Üh…[…cÏ·ŒÁÏµâ¾…äïOÏ¸‚S_±_àS"   ,
	L"Xš@À…¼šâMãÒ‰I—ÌôªÚiÏ¶øœëìù½”ÚVëKŸ¼ Ì·G‘ï•ÀÊ“ÓB‘ñü_‘ò´ŽÌŸðqô]‡½êSìUÐaÏºØB‚Òéi”¯ŸïPÏ¹ÎröyÏ»ÏÀáò‚bÏ¿èÔžÙÏÁêƒ{žþªM«”µ„íÌ¸—ÁŽÅ{ê˜œÀ³ˆåÚ“ŠÏ¾è¦¹d´WÅrÏ½¿EÊ›¿[ÚYô Ý å’"   ,
	L"XÏ¼æ_÷ïòhúTépBÏÂÏÅˆY¯KÏÄ—B²LÕ’‡˜‘³óÁ‰ìç]ÏÉ™ŒÝÏÈŠhÏËÙüë¯–}ìì¶iÆxôÌ«ˆÝ²ÏÆèõÑõ£ÏÇƒMƒm‡Jã”ÏÊåßí„‘œåv¿ÒDí†õrñMÛŸ‹ü`”s×]ÀoúNÒvÜ]Àw÷€Á…ûÏÐŠˆÏÒÏÍÏÌ’¦ÏÑÃjæµŠÞ‹M½L"   ,
	L"XÏÏÍpÏÎ†¥ðïÍ€éeðÂÏÓ®Qã•‹¸‹¹‘“Í½ÕtÙtÖPÝá_°B°GËûyµUÚDèvú‘ú’úšÙþªAÏÔÏÕšÀžóáýò¹ê“Ú`óÚŒ¯Œ°“{µ Í˜õÐ¹‘ªªžÞºå‚ìÞî‡ŽÒ”g™ÌÌ\«Ní`ï@ž¶ÏØá­ÜÈÏÖÏßÅ`ÏÞŠ«ÏÜ±hêˆ†ZˆŸŠ½ŠÒs•›×"   ,
	L"XÇ{ÏÝ¬FÏÚ±•½mÀ‰ÏÛÏ×»˜ÏÙƒgƒn¾QÕ^“È¾€ä}‘—˜ó¿håDðWØRžnÅ@«I¼`çoö±ýEÏçÜ¼ÏàÏãà_Ïá†“àlàmŽûÏæç½ÝÙàx˜UËGÏä¾|ÄÏåÝæøû‘™Ö­Ïâ÷`è‚óJ­˜ßÏêâÔ–ÙÏé½|ÏèÛKÏí‰ÏìÍJâÃ•}÷ÏÏëã}ðAöß‡»"   ,
	L"XÏ†õœí‘ð‹ð“÷zÏòŠ¢ÏïÏî«“ÏóÀ‘Èeí—Ïñ„âñ•ÚÏðÒVó­ç}÷Pž¼ž½…ëèÉ‚PÏ÷ßØèÕæçŒnÏüŽé|Ïûç¯ÌåÐû^†’Šë—nŸ^ªVÏô¯e¯hÏõ³‡·›Á›ÈpÏú“`½‹‡EšRäìóïÛX‡^‘‹“ßª”äNÏö–Ä…Ê’÷Ìø{·nº}ËrÏSÏ]Öyø“"   ,
	L"XÏùžtºÏvón‡Æ‡Ì™ÏóuújÐDò”š®Ì‡›©àUáÅÏýÔFÕqÐ¡Ïþ•šóã¹q°~•ÔºSÖj°†Ð¢Ð¤„¿†Dk‚jÏøÐ§Ð£›ßÐ¦Ð¥‚å”¬œøÔ‰‡C‡VÕ[‡[š^Ÿê”Â”ÃÐ©Ð¨ÐªÐ«Ï„µÐ­”ýÐ°…fÐ²ˆ•ŠGe’’¶Ã{Ã|Ã~Ð~ÙÉÐ±Ð³ªn½eÁ–†à"   ,
	L"XïÐ¯¬€½’Ÿ»ÄnÛÄß¢“û¾™çÓÎqÐ¬ÖC X”XíPÒp”yÀi×ýšÐ´ƒæŒ‘Ë†ÄžÂÐ¹Ðºµmç¥À‹Ð¶žàžá…lŠÀÐ¼ŒÈ‚ÄÇÐµŸc¶cÙô‹rŒÑ“aäÍ½uÐ»ƒD‰féÇé¿Ñ€‡ƒŒÔ•»í…ŽOâÝÐ¸Êâ³¼IËZÞ¯åâÛÆÒCÖx‰êžaå¬ yÐ·Ï’ý^ýk"   ,
	L"XýKÜaŒÚõóÐÄß”Š|ÐÃÐ¾ÐÁê¿–‚ÐÀ±^‚r¹âdÐ¿ÐÂì§Q‡Œ‡‹×Ð½Ü°öÎñQ–“ôgç†²€êc¿Ø¶ŒJžÔÐÅÜŒÃ’ÐÆÔMŸ{ñ^Ågîˆá…ÐË õÐÇˆžóUÐÊÐÉŸ“¬wÐÈÍÓq¹“¹žÅdÖ_•ÛÓwòH°‹ÐÌÐÏÐÎÚêéàD†QÐÍ›™è—ê€ŠÈíÊ"   ,
	L"XÑRè™â]ãoã‹ät²MÐÑß©ÐÓÐÕÐÒÐÔÜô‚†ÇnŠüã¬›ë‰D¾m‹ñÅBÐ×ÐÖƒ´ÐÙÜº×›úÐÚ†Mr›°ÃrÐØÔKÔžÐÛÐÜ×œÔw‰é”¸ÐÝ‚cÐÞßÝâÓžñžòÐßÃƒð¼Å^õ÷âÊ˜¼ã–ó…÷ÛæTõxø ð}æ™ïqÆvÐà½œú¼NÐãá¶«‹ÐåÐä¬LÐâäå½‘"   ,
	L"X­PÑfÎ¿ÀCçVçnýMÐç•B¯Líì™øñãÐëÓ’çïÌÐé× ‹€Ž­“TšHÌ“íš—ì· íœÐê·PÐèôq‡uÐæ‹Áš[¿HÊŒÎdš_ÕšÖžôzòè`ôP‚TÐìÉ[Ðí…éŠÚ¼ƒÛèò«‚»ÔSœ•• Ô‚à†ôÚõ¯±SÐñÅÐò›Tò…r›UÐðÐô•däªˆ¦šAš~ží"   ,
	L"X«—ÛÃ„Ô”›”¢ŸTÐ÷ÐøÐï†Ä‰ÙÐö•ýäÓÐõÔ[Ðá‘Aìã¾AÐîÙ[˜s…±N²W¾wÂ…ã„·V¾{²xË…ÀmÞ£…ºÐù•R†IÐû•tÜŽ—]ÚÎÐú‰H‹lËÐÞïÝæÈkêÑìÓ¬uÉ{²UÙØ¶P¹ŽÂAÎh‹ÖÊžÕÖXæMòC²ÂQÌBÌTÏ×Xö~×zÐþ«tðçÐü"   ,
	L"XÐý¬IÍ•‹Ÿäö•Ãè¯™e­v‘ÒÑ¡Ÿ@•œßxÑ¢°_Rãù•]ìÅÑ¤Ñ£Ðžîç¬K±†ÐfäÖ½ké¸ãCíÛÊRïàìœïX¿¿’æ›ÚK¯TÉHÑ¥Ñ¦íYÑ¨”ÄlˆyÑ§ŒúNÆ‹í´Ðû`õ½ŒWŽGÍ KÓ{ëzú›Ñ©˜ÝÄ}Å–ÞG÷¨÷LÑª…ÉV›‡ ü¯N–ùžûÚÊÚp"   ,
	L"XÖožyˆ_Ñ«Û÷Ÿ[„×‰_Ñ¬ñ¿ÊM„ë„ìË`ñ‡ ‰¶â´Þ¹êÖ `Ä²†ÌQ‰Ë oÀcõ¸Ñ°Ñ²Ñ®Ñ±–hÑ¯á¾âþä­ä±¼rÜ÷–Õ—Dš½«‘‚ÅŒ¤Ñ­“MÔƒñZà‰öà‡x”˜ßŸïŸñ @­RÒWÏy÷S÷\žµ…_ÑµÑ¶¾Ñ´Ñ¸ùáßªFÞ™Ñ·Ñ³ÓÓ–ÓœŠQÙã"   ,
	L"Xš¦ßdôÙb‡eÞ¦îšèRÓõ"   ,
	L"Y…¥ÙŒµK×rìaÈC‹jÈ€¯uéœùgù“••›¡‹‹Á‰¥òˆîY¬„Â]’…ìÓ”‹P‹’F•iŒßŠ´ˆ×“~é‘Ÿ¸ŠmøNÝ‘‰àŸ‚ÐMœÄÑr¾ÏX›þ‡©™ö­’Ýk†¿“Ní‹ŸºÐ„ŸÑ‹ÍY‡‚²ˆ’~«lØ]ØbŒ¢½ÄžìƒeµÇo‚\›s“AˆRƒhØ‹ï…ŠxŸ]ç~žÏîƒ"   ,
	L"Y@ó–˜·Ø‚™µÜVÝ`”^‹ «Q–ü«DÝr’íŒTƒŒí±†Ç‡y˜®‡§è›Sý{ˆøÛpèŸåWÑv¾_ãUÄdÁm“êÚ_šJšüÁ”ÎƒÝl™LÊ‹ÆÊäJä„’´ŸSØßÍF¿IÀK÷jâPãA¹•‘÷ÖuáŒ†dÕfÕh qèp—V¹SãB«}•@åUœ«„üø˜ÚŒfãŽ—H¹c‹U‹š†"   ,
	L"Y„Í‘›â’L’¨’É öÞÔq±†œ^›ðŠ€Œ² V¬^¾S…y¯_Ëe…°˜XÞdÝ˜Ýœ„ØÄŸ›@›AžõšT…ÇàNŠÓŸyŸÁÕOš]”¯P´l‹ÍËW†mœ¶ÐjëUŽM³wÁwüGÔ”lèH›ª¼œ½X¾ŠÔDÃ‘Ñ„Ñ…äPªËv÷r˜CÞje¡Ñ¾Ñ¹Ñ½ŽâÑºÑ»èâÑ¼ŒS"   ,
	L"Yè›—¿øfåEø†‰ºùsçŒÑÀØóá¬Ñ¿…ƒ–‘çð¸ŽÑÁˆÛŽÑÂÑÄªc¬ˆíýÑÃQý\…|ŽÞÑÆ†s†¡ðéÑÅ¯{Ê‹„²ˆLÑÇ·ŠÒÑÈ„ ëåÂ†«eÛëæ«’¥í¼‚oë²ˆº‹I’éÓ ÞëšåªmÂyˆB¶–¸Eý…ÑÊâû„‰ÑÌ«ŠëÙ‚¹áÃÑÍÑÉÝÎÑËäÎëçƒBŸŸ"   ,
	L"YÛ³æÌvö˜ÜáZéŽ‹éºc‘±ÅEüiÚ¥ƒÒÑÓãÆÑÏåûÜ¾ÑÔÓ…ÑÒ•VÑØÑ×àIŠ¶ŠÔªPÑÐÇrŠ×ÑÎ¬J³xÔPéZÑÖ»¼óÛ½žÑÑ‰c“C—ðÔ´NÊBÑÕÌšé…—éÜîî†‡À‰ÁŽiº™™¿û’‰ÌŒEŽrŽsŽv™ëµhû}ûš‰ü’Z›WmÙðÑÙÙ²ƒ¼…]m"   ,
	L"YÑÜÙÈØÉÑÚÑÛÈTÛ±áD°Ý‘þ“R—¦œ{œçüßVëC—ã³šî»ÑsÑÝÑŠ‘îÎi÷Ê‡{Üy¿t™•üd…˜®[öoùžüfýdýŒƒ°üjükî›ýBŽt•óô|÷úýzüsÑáŠzÓ_ ²Š°©ÑåÑâÑäÑçêÌÑÞÒÑé‚©’ïŸgÑèêš†ÍÑß”©ÑæìÍª_³ŽÈŠÑã—âäÙøH"   ,
	L"Y…’‰†•¶ŸÌõ¦‹ÇÚÝ÷ÐøeŸðÑàÖVØÍôe•àø‘àòVòY‡²‹÷ÆFÙžÜ‚ wázòzú`ž¥ÚIÓƒ×…á€ðòžúŽÆGž á‰óFž·×—ØVØWž¹Ñë…óŠš’tãóÑêÃo±jÑíÑìãZë‡÷±å}ø„ÑïÑòêgÑô•DÑîì¾Ñð„½šÞÑñè–ïrˆ”áà•[ÑóÁfìÈ«Œ±ˆ"   ,
	L"Yê–¤§“PòÕ”®•ª—îŸ¬¶@¯ƒÖUÝŒåø—ï^ç{öuìRûF…nÑöÖˆtŠIŒ÷ÑøžæÑõÑ÷½D‚ê˜DÝIûšçÁyðBñ‘Ä”ažY°WµSâó–³í¦ÑùÁkÔh˜”Ñú˜ÓçÛØ²ßºÑý–”µnÔ@†ºÉ@—êÑüø^ÑûØ³Ò¢Œ¸ëÈˆÒ¦ié÷‚xž÷çòÒ¤‚çˆò“e"   ,
	L"Yš¥Ò¥ÝU†Ú‹„áæç“uÒ¡ªrßbÒ£“Á•¬˜l¬ŽÑþã“ïuïŸŽAŽCÙ´t¸G¸HðPôíÖ{Ö|÷¥ï_Ìiî–öŽ¦ŒaŒë’qèÃš| úÆwÒ§–Ì±l·ñºÒ¨‚¶‹QáÊœÈ˜eø€é™ò[ýoúr·ŽÒ©ÒªÐ‰·š¹OÈ™ÔoŸÆÒì‰ª’ðÎËaýGê× dÅ—ËŽ²‡•êÒ«"   ,
	L"YÀfú_×Šè€‚œÒ¬•¢Ò­£ÐJÒ¯Ò®’ÀÞÞîô ”âXäyæU”IÒ²…½ˆÒ±ˆ¸Ò°‡Sc‰­ÒµÒ¶Ò·Ò³ÚþÒ¹’w‹–¥›í“êÊ–¦ìÇÒ´ÒºÚËˆìš‡Ò¸È~àv‰¢˜G˜Iñ@ƒp•Ï•ÐšSŸî”@°‡²wà’ØÌŽIŽJÖÖ]ðY‡™”L•â²|æE”K {µBædðvùw"   ,
	L"YìvóBûEÄŒŒèÒ»oÞvñÂÒÁÒÂÒ½…À‰ÒÒÀµtßÞ›¥â¢®ŠàcÒ¿Ò¼Ò¾ì¥Í~¶B‹¡äô·Fãž‹Âàæ‰ß­Cûp¿ˆ™š­át÷ð×búsüpUÒÇ…FÛÝÒÄƒÞŒbÒÊÚ±îÒËâù›n ôÐtåÆâÂß×ÒÌ[‚q–ª®AÜèêÝÞ–ŒhŽƒ‘ü–Ø–õíôÒÈÐ‘ôýðê"   ,
	L"YÒÆÈU‹f—×ÁrÍ†ÔrÙOÒÅ•—àÕBÛDí›ÒÃïÒÉƒxŸÛßzŽK£¤Î’îUîVŒ–áÚºmî{õkÒÍ¥Ö–çF»JÓ~×‚û@ÒÒÒÑÒÔÞ~îÆÌ”ÒÓÜÓÆqŽåô¯ÒÏáÒÐ‘ý¸”Þ ‚Ã©”îÒÎârãiøCì½Ý}”¹Î•™}µEÅœÏî‰ÞTýtVÒåÒÚß®Ø×Òä"   ,
	L"YÒÕØî„ùÃEÒéêdÒà±ÒÙÒìæÆNÊØý„·ß½ˆ`ÒÛÒÖ•ö–pÂkÆiÒëÒØÙ«…å…êá»@âøÒ×–›užËÒïÒèæä‚XÞÈŽ•Ž–ÞÄ–¤›¶«pÒßôàÐzéó†jˆ£ã¨ÞÚ–å™ý›Å›ÎÒæÐšÒêØ—ê‹„ÖˆËÛü–š¡®Ápñ´ÒîÈ^ÔTÔUØ[Ø\ÒÝâNëc"   ,
	L"YŽ¯”§•”—©š…œ™Ÿ|Í‚ÔmÚ˜âzó`{ƒÏÒâÒçª~¯m¸vçËÁxÒÞÒáÑ`Ô„„ã‹M˜]ðùÄjÉšòæìˆñkƒ|“Ì˜¯ÒãìÚŸÖŸé¯ŽÕxï×ûkûoü]ØæˆI‰©‹Î‹ÚŽF‘›‘«•ËéìÛ D¯–²e·j¿OÅ’Þ²ÎœÒAŒ•”¾•Ù™jšc J WôèÒíÒÜØŠõl"   ,
	L"Yñ¯Ë„Ë‡Ù“æ„ïîÀXÀ[ØsìJöGù€ùù‹ž‹Ì[×g×háyá{ð†‡ÒèOú^úgÜ²Ò~óAú…Ìˆúœ×”ý~]‡àÒòêfÒõðˆŠÒöä¦ÒðÒñÒôóS–ðÒóë³êŽƒø¶†ÑPî÷ê”ê›à³Ü§‹AÖ¹N½sšPœÞµšÉMÊa‘@¯ŠãŸ´€¾žìÖNë–ñ—‡‘ž@éžë í"   ,
	L"YƒÜÒ÷ ìÆgÛó›Ž‡ô|žôáþ«»ƒÇZÓ—†‚‹HÒú•ŸÒùÔCÒøâwý‡œô´HÛ´â¹Ê_ÓÕzãyö¸‡wš’­K‡¨™ƒÏrö¯ý]ýlúÒüÒýßÅÒûò¾Òþœ^âYâiï‹ëLì‚ï‡–@Úy™añ«ë[Ž\þÏPÌa™Ó°a×Ó¡Üá›Ø·ˆ¤œšªZJáS‘\°E‘€‘"   ,
	L"Yõg‘¶™’Ó¦êÓ¢‚Ÿ—@«›Ýº†¦Ó¤‹káœ€À†–PŸ–çø‹”´QéAàÓÞüœî®O¾xÓ§ó¿ÎsÙaÓ£è¬‡|À”Ñšë›øŠðÐ‹ë‘ªâßíŒ®ZævÓ¥úD‡Â‹ýŒ[”tž‰À›Ìc™Ñ­‹µ_×súLè]ÀtÐNúˆÜ…ú—ûKûW°ŸÓ­ÜãÓ¯ÜþÓ«Ó¨Ó©ÓªÝÓÍw†Óœ»œÁ"   ,
	L"YÈtƒO‰LéºäÞÝöäëŸÉÓ¬¬“Î„Ùø I¿MÎžõöžLËpÓLÖhÓ®Žc”l”wå­žuž„Ï‰™Õž¡»Yž­ÚA»k³AÛ«—wò£ïIÓ±“²Ó°}ñ¨·fîeŽg_ç°`Ó³•£Ó²ëôÄ{ì™ž]×GÓ´à¡†ÑÓ¶ÓµÓ¸çßÓ¹‚ò†Þà{ÓºÜ­‹£ã¼K˜Ÿ œ‡‡ÛÕ“íÑ"   ,
	L"YàaïÞÓ·°MëtçO÷«bžœ÷Ó÷Iúx°bà¯ïJî„öÓÀð®Ó½[Ó¾Ù¸ÓÂ„Ê–Ôˆ¬~–ºÓ¿ÓÁ‚æ¾Óœ¥³‹Ô‰MÓ­òÓ¼úÓ»¶H÷‘Ûxõ—ÓÃÆo³lákÓÅÓÇØüßÏQ›|ÓÄÓÆû~H‘nƒžà›‡¦‘ÉžX™¢ÀlÂiÞÌÓÈÓÉ›YÓÌÓÊJÓÍÃUM"   ,
	L"Y”åèÖðàr›Á¶xÝ¯ÇxÝµÞœà]ÓË‚ºòÄÔIßKÓÎªqß[öÏ˜Aéà÷†ÝjñfÊ~òöôœÝ’õO™ÔßˆÓÑÓÐJØÕÆhÓÏÁhŽîÁgÝ¬—XÂuÃ…îðœ±ÉKµ™ÍœäB˜©ë» ¨÷îÓÖÓÒÓ×ÓÓÙ§ŒM û¼n†NàóŠµå¶f ¶µvÓÕÞ”†e—`òÊŒØzÓÔáRÕT÷ø"   ,
	L"Y’GæúÓØÞ}·‹ê|¼uÍG†‰ÓÙ±EÓåðö¹zÓÚ€ÓèßŽ­Óàæ¥’T–fì£«]«_ì¶ÓÛô§ÐsÓãÓáƒÊØ®óÄô¨ÆœÇSŠÊŠØÓéáüÚÄáCâÅÓæÝÇâDêœÓçö§ô~ˆèˆï£·áÎÓäÞí˜KœŸ®Œ®³†ëéÓâó^ÓÞ˜@ÓÜšQ ¢è¤Å„ÓÝêìO²Iñ¾ÓßÑˆ"   ,
	L"YšuÁ|ÊvòõÕ˜ëkðNôˆ‹ä‘µÄÓDÛuše­mÏLÝ›å“µHÖ~ókõ‚”ù»BòeöVöiú}ûCÓëØñÓîÓìÓðÓê‚RÙ¶’§ÓíÓïàô}µ€‚¦…Pàöâ×” àhÈgÈhèž‚øŒ†”Ñ—å¬rðõÅcÕZñÁäoö¹‡‰ŽZØ…”Ëû‡ÌPýrÓñÔ¦í²ÓóÆRåýóâÀÓýÓôª"   ,
	L"YêÅÓü¶rÆ‘‚qÓø–ëÔ¡³_îÚÔ¤†¸ÓòˆÖƒ±ÓûœMœUÑ@ÚÍßNãÐ†³†ÉÓ÷‹VÔ¢Ž÷Óù—™—š—§Ÿ~¬Z²œÔ£Óöï„ñSðÁÓúœùìÏ·CÁNÉfÝ÷Óþâ•îA‹žî‘íØ¹ªz¯¾sÎCòâÝhãƒëT‡o‘j·UÉ™Ê Ô¥ßyä`ø\ËŸúìÛÊšÖIå[é“øƒø…"   ,
	L"Yøˆƒ™´›¶RôrðÖ°KµN·{ºh¿›áqùO™Èð|Ì]×uÞXçŸìM™äòå÷»Z÷Nú–ûO™óÜ†ôcôdžº»n Œ‡äð°„uÔ©…€íóÔ§ŒwœaœeÔ¨œm­œYÉA—¥ÉdÍ›ûgóîøSÎQñrä‘øx‹õùtž”üŒüÔªÚOß–Ô±Ô°ãä–zÔ«ë¼Ø’Ô­†TÔ²¸ÍWÔ¬"   ,
	L"Y…ŒáJ‡ûÔ®œ®ªjÔµâƒö½ˆ@ˆAÜ«‹…‹Ô´œÆÔ³ªxÉV˜g˜rÔ¯¾‰¿FÎmÎzô’éÚÁ~ËQó¢ÖwÞ@üxæ…™´ß‡ò{ù úM…™Ô¶±\ßRßh‰íÃOŠ†Ô·Ô¹ÔºÛùÐc‚ÓæÂÞòè¥µžÔ¸ÑjÑ†Ñ“‡…îŠÔ»•õÔ¼¼s¹–³E¦§ÔÂ‘àë¾Œé’`µjÔÀ–†«h"   ,
	L"YxÔ¿‚ÔÃÍQÍRÜ‹îáÔÄ’ÕÚ”Ô¾ÔÁÔ½â_»›ãXé†é‡‹íéÐºMŽ[Ùß»Cå®Ìgüg ~¶^ÜS»aûN»lý›ûVÉCŸ±ÉQŸ¾Š[Î‚ÚSîfñNÙšÔÆ„òÔÈ»…Ô‡çŠu’l›Vç¡Ü¿êÀ®s±d¶nÔÇ›é¼‹ÔÅÂmàyë…äëµœÝ¹oÉlšèŸÂ·Ê|ä]˜øºJ¿a"   ,
	L"YÀIÔÊêmŠ@’dáñ«jÔÉÇ\éæ†½âqëEšŒÑŽña´pìBýqýyÔÐÔË–—Û©ã¢ÔÎàiÔÍ‚ÖÁã³Àˆß\‘C•žÄZè¹ÔÏìÙ¿AÊ•ÔÌ¿ZÊŸÙ„ádájðaËœíríyÌNíß@"   ,
	L"Z”±’Ã‡ÍÖ…MÊiƒÔ‚È…‹Žúò’K’·“cÛ‚Æƒ]™Ù‚t³¤ŸéLéMü…ü{ÖšÖnÞêâ\Úf–bÃw‘~»Ãq½‚›‚šlßgßtÞŒ×rÑ~¾…ÎuÏx¼—“o—¹Ô—Ëg‚¸ÆcãIÊx‚÷úE‚…ˆ§¹Šæm¼ƒœ·åÁÄJÚ}ýwódËF›ÚÄÉ˜ºŸÐ¾‘|ƒœ"   ,
	L"Zõ¡‡m™ç·‰ºeé˜§º‚y¼¾\îx‰–’ŽÛZ±‘ÊP„‘ÛünáGÁŸºa’† ¹Óh†“ŸÎ[ÛyücøJÕ{Ëyà©Å\öl±‚ü‡–’„†ÂZ´qê ÄR‰ïš†Æ–Ã˜ÞÃiÚâÚM‘ßœõ²G ³ÚC‹¥†‘—ù‡­uöa·}—ä´DøZðe–çÑIžRžˆçZÀU”T¸tøF³^É›"   ,
	L"ZýeIÛBÃëh’ÁßI®›láB×`óGªK›m“¯Â™‡ËâW…µoÍVýR´„â`Öt¾PÀRÇŸˆ½ÝXõ›ÇŒþwÛI®l¿‰››ºd¹€“””zãJŒ×R~âžßmäK™yË\ËŸúžŒ¥ÌŒ²Bº‹ñ~Ç Òf Ã‹qËS‡¢ç‘‰\GÂzÛ@âŸãnª‘·r¤„Œ„–‰t“»`ºiŒ¾"   ,
	L"Z•H†”÷ï‚–lñXóCêuÈ[ÌEÂvî“áWåM“ë’V–y†A–žõaíCä\õSö]æcÉ|’Å‚´“ü–sŠ‰¶h–ñÝWZ”Õ›ÆäVâ™ˆSšõŽ‰ÔÑ›eßÆÞÙ›j–ý¼’¼™ãNô˜ÅHÅNÔÓÔÒíˆëj´’ÒSës‡Ùë{žÄÔÖçÞÔÕÔÔžüÇœ…œÖ²PÙ†Ô×ÔØáÌÝdÔÙÔÚ’D"   ,
	L"Z›’‚îáPƒ„¿fƒ³ôØô¢ºç‡ÔÛ‚Ì†¹êÃŒv“Ëƒ›ÔÜƒ­”€ôõÚŽÔÝ•ºÙmÔÞöÉà™žUÛŠàŸ­ÙçYè¶áA‡Ôž£×{­‘¶`Ò{×“ð• ™ÁnÔßÙ_ê°ÙjÚEóvÚNæàñzÞÊnÔà‰ZÔáäQÄ ÅK‚óÔâÔãÛ›ásÔäèÔçÔæ–ÒÔé——­FÔè­bËkÔåÔî"   ,
	L"Z°oÔí†rßðÔì—_†×‘VŸ¯ÅÔëºrÔï¸Y×YÚ‹Ôê¸^†¨ÀÔò’k›gÔñ›zÔóÔðåÅ„t†‡ßõàýóÐô·ØŸœÚ²ž‡K‹¨Ž¾óåÊj˜ÁštÕ‹ØÓ“ñÉ°ƒ²cºjÂd´ŸÒ]Ö‰Ù‘Ïý`ývûBØÆ‰÷ŽÙšòê¾•W’¾¡¶ÔôÙ\÷ŒÏŒöf÷eÔõÚÚ×P×U‡×•û"   ,
	L"Z‰ˆà‹ÔöÔ÷çÕ™IŸå­Q³D´ŒîÀ¿•ÖŸ÷_ï­ä{êµÔùÙ›ß¸ÞÕ¦’s’Ÿ–¼ßî‚¼ÔûÞêÔüœÑé«„ž°•¹†˜ÏÓu°š×A÷þýOÔúÔý®hÔþÜˆÕ¢ÍlÕ¡Ÿ¤ £élëåŽ×Q…~ÆzÕ£íÄ“ƒ÷‡÷ÛzõWõ~Õ§žÁÕ©ßåŠL–ÅÕ¨ŒoðäòÆÔp“’“«Õ¥ám‰ã"   ,
	L"Z»y’ÆÕ«”ÈÕª˜zýSÕ¬µÔÕ­ãSÕ®íÎ‚ùÕ¯ñ©Õ´Õ±ì¹–îÕ³Ítï¬ÔaÚjÕ²énÚÞ‡~ŽEËUßë•šÖšØÕ°ûr”ö×dðŒø@ò ô}÷gûD×–’€Õ¶ïsÕ¹ÕµÕ¸”Ø¬WÞø±Kãä˜^Õ·ïQ‹¶á\˜öÛ…Ýš°œürÕ¼×Õ½Õ»—CÕ¾‚·ÕÀÇ•—£Õ¿‘é"   ,
	L"Z¾`øÝu‘ðÌ›ÌœÓOÞJÕºò–ÕÅ{ˆÕÂƒ@ÛµæÑÕÃ‘PÕÄâ¯» ÉŸßl•ÀÕÁè°ð\ó¯çbò†÷Jû–ØëÕÇ›îÕÆqŽÇ´˜ì ç•ÕÉÕÌ’EÕÊÕÈÕÍÕË»wŽ¤Ã›¯oÕÏ‰záÖá¤Ù~¯“ÕÎ²dÔîÈŠ„Ž‚ÕÐÕÑžÝ±@á“ßúãDñq¸Så™ ÕÒÕÓ¬ÕÙÕ×"   ,
	L"ZÚ¯––ˆªDÕÔóÉÃA”íèþÀ’ÔtÕÕÕÖ¹|ÕØÃDÚw•× Yõe™˜²Á^òØ‹«ÕÚ…zÕÛšy³K³Y»qÍEÕÜˆ³»„ÐŸ†£†•†•‡éü†´—‘ÕÝÔ€ÚØß¡Ým˜µíÝÝtäOÕÞÏU‡¬Ö†Ö•õ„ÞH×yÒx×„ÕßÕàô÷ñÞæNÕâèÏÕãœJ†øÕá˜ÎðÑÏVúpÕêÕëÕì"   ,
	L"Zä¥Õä«‚Ø‘Žž–×èå±wÕæÕèìõá˜‚É”ž—FáIŒzœÈœßZ“ŽÕå˜Eª€ÕçµÉRÝèâœìké»˜ˆš‹¬‘´U¶G›óð˜çØÕéËmågÝŸåŒæP»E÷yŒÇÕï’rÕíŠª•_ëÓéôî³Õî±pÐ½GÂrÈZÑ]Ò˜Ô\ÝF‹çÇð¡ñ}¿b¿jÞtôIümÛÚÕóÀƒ‚E"   ,
	L"Z’™ê‡ð²ÕñëÞ–Ú¼…±‡êâ‰`“L½„Í–”´ÕgÙcä‹ÕòÕðøcææ‚ül„JÕùÍŠ’Õ÷Õú Žá¿ÕõžÚÕøŸA±kîÛˆÁ”˜’êªbÕöÂtï£‹o“@óÝÑ± Õôã`Õ¹~áçÛtºPåPô@°Yšé’c¼lÕü’ð‰^•“ñ“ÕÕûÕýÖ¤ÚºÖ£Ö¡ÕþÖ¢Ž¬Ô^àÕŠ"   ,
	L"Zøg×CÖ®Ö§Ø´Ö­Ö¥Ö¨Ž›DÖ¦ÖªÖ¯Ö«¿èÙìó¶o¶qÃeëÕÐ}Ð‚u¯Uµ…¶~Ö¬ëb—d‘ç—ÐÅ]“w¶A½˜uÖ©ñ\øTÖ}ø¿—Ìuü~¶_Ö´Ö¶ˆpÖ±Š©‚ŽÖµÂpá™ÛúˆÌÖ°Ö²Ö³µ•ôêõÅ­•‰~Þýñc‹À‘eZõÜ˜àÄˆ¿{ÂšÏdÛ•Û—ÜÜUÖ¹"   ,
	L"ZÖ»„M„¶Ö¼ênÖ·ˆ^ŽŽ’W›E›bÖ½ÜÆ’nìíÆ‡åëdÖ¸è×›œ³Uéòœ]¯W¼ˆÔJÖºÝTíéõ¥ËŒÒjêeÖÁÆWÖ¾âå’XõôÖÆ…„ˆ€àùÖÄÖÎÖËÖÊÛ¤‚fÖÅŽæŽè’”–»èÎ›±µwÚìŠÍ¼Ö¿•yèäªOÖÈÖÂÐ—êÞéùv‚ÀÃÖÀ—„ªa®‡ÖÌ¶ƒ¶ˆÖÏ"   ,
	L"Z¼•Á“Ð˜ÓdØ èœðº‚ÐªåéÖÇÖÍðëòÎæïŒ…D“ˆœí¶žÖÉ¹eÖÃÛNÝeé@ïô‰y˜—œþ†¯F¯€ÑuÒžÕIã‡ŽÃ‘p“´žŸÜ·Wëùö£Ù|õÙäk”òž\¿@ë\ñ‹øvƒœ„¬‘Á”S”`™±·aÏH‘ÆÙ—™£­}ÓzòsöSµYØTòòŽÜWúvèeØUÖÐ«›O„d"   ,
	L"ZŠq³Þ‰ÖÒ›wžÆÖÕ–°ÖÑÐxÖÓô±ÖÔ½Kâ{ŽºÊWïñÎ ø‚ó®æRü™Û çŠ»bÖ×ÖÖÚ£†ÁŒ»‰VšpŸŽÄ[¯~·NõàÖÙÖÚŠt ðµrÆ Ð{ÖØÍ\‚£±Šˆú‹g¹WÐ\ÖAÖÝÖÛÖßúÖÜ›ÖÞžë×žžö«‰ÞbàX‹BÅœ@³BßLûb†µÖàÚQÝcã{ÙkÝqë“"   ,
	L"Zñ™‡œ±TÖaù@òL×pæ¨ÖáÝSíØÖâÖã¯JÈF•Ž²H¹öBæûÆ…âÖäÖæç§ƒÙ†BÖç¼qëÐÝ§•ƒÖåôü»‹È’Ôk®Lƒu°™ñt‡€¿UÖèô¦»Q»NóEÖì„¸ÙªÖïÛ¥ä¨ÜïÖêÖéÖîÖí³pÑNîù½ZÖëÕDÛHéÆäóÎwãéÍÖTØiñ–õfø–žzË ™½™Áü}"   ,
	L"Zö^ÐEÖñ›{óÃžÛ¸‰ÇAÖò·”Öð¸˜ô¶ðñÉ TÏŽõî÷E„±ŒFž¯”á•ô™î ‰ÐWè“Ö÷ŒeÖô³dÁCê•ä¾Ÿ—ÖóÔ}Ööî÷æÖõŒÙ‡Ú²šØùÐ×¡ÖúÀ‚Æ^ÜÑˆ|èÌ×¢ÆrÖüÞŽ×¤‰ÔÖù–ÇšŸìÄ×£ðæ±vµ‚¸mÇd¶‹¼Ÿ½AÁqÖøÖû­ÖþÔ]ÙAÚŸ"   ,
	L"ZÝOÖý¹hãLïŒñ[‰£óçôã˜ÖäŠñvºBºZë—û„èT×¥™tÄºœó˜×¦×§ÛJ×¨…¡ŒŸ×©Œ£à‹§­A®UÄxò§´uÖKÏmî…÷H×ªŒNÜž¸|ÞDžÀßùˆæÉE¬ƒƒQ×¬×«×­âÍ¿xÒNÙ×Nð‚‡Ê»M×±×¯ŠyŽáÇPŠÏ×®Çfœ³»’×°Ñb˜¶¼PãÜ×³‰Ñ×´"   ,
	L"Z î‰Õ—[Ÿ`´±×²‘Þö¿×·æí×µ×¶åFòKùx›d×¹¸ŠÜ×ºã·®IçÄ®•³›Äi‰‹¾Y×¸¿PÕ…á^åYðU´œÙ˜ÞVèVŒdÞ„ëÆñ¸×»ÕÐq×¼ˆÍƒýœÊ¾MÔR¶›×¿×¾žãÙ¾×½×À—‡äÃ—¬¬k¸B˜‘·q·‡ÐXˆV° æ×Æ…¬Šƒ×Âí½×ÇQä·ŸOÚÂ×Ã"   ,
	L"Z×Ä†Šß—z×Å”Ù•Œ—Á×Á”Ú³˜·ŸÁM“â“ð”Ûìú„ŸÕ}ÕŽäráºWßª”½”Þåª™·Ö‘ïíè@ùhž•Ï—èC»Sú|»m×ÐŒI×ÎÆ†×È×ÉŠœ×ËÆ–ã«R¼|êß×Ê ×Í¶‡ç»ÚÑÚa†êæÜáÑ—Âœ¹×ÌÈŒê¢àtŒUµ›õþÙDÙYôôïÅ·T¾lâˆéCö·Ýwüˆ"   ,
	L"ZÐÖJÚƒÝ–åO÷ÚööæSætîoîpõ™ùƒýUö‹ýb×Ñ×Ó…»Š—æ¢–j³I¶fÃc…èïöñèÍIóÊè÷âB†×Ï×Òö¤Ô`˜h™U×Ö×ÔÆTÆ“‚•„í§ ¼×Õ±{íö*Ãun†€×Ú‚×ÛóWˆî¸¾È×ØªfëêÈ –Q—ÞÙ·O¾C¾hŸÙ¾›ÂCÅ‹ÎxÛr×Ù´†Øq"   ,
	L"ZÛ™òR××òiôAôiöRö`èQ×ÜÙÌ’Ö¼ß“K“i‚ôÉ~“¨¾t¿G Q¿‚æCçE×Ý•f¯S‚~ª`³ŸôÕ¼F¯—¿kåS¿v×ÞæãÚÁàYÚî’ôÇˆ—¯—°àu¹t¾jÕŒÛ¸öíöOüPò|ýÚ[×ßõ•×à×á‹ƒ×âÝÏÈ{Éa…a×ã×ä†XŒœ×å‚ú·B¹ŒÛnÛ€ïßæ—×ç"  ,
	L"Z×è×éÙÞ •«~×æ½MÔ{ì†æŽÖŠ„®õòèjÜgèÀFçÚ×ëÀj»gÀy×ê“Sß¬…‰–K†÷˜áÏ`Àxê×ì‡’û­r–˜–è½SáE•×îµ‘×ïÞfáUÞ©×íŽT™däŽå@™i·s™Þ×ðý×ñé×¿ŸÀ–ùŒç÷®÷Vú•ƒV‡gß¤×J’Äã†×ò¶}Çg’Û—½Èy¶š¹iâ—"   ,
	L"Z×ó×ô¿–×÷×øÚèŒõŒöâô‚F×õìñëÑßò×ùÐŠ×öÈzÉïŽ¼d…ø"
};

#include <atlmisc.h>
#include <atlddx.h>

class CPinyinDlg : public CDialogImpl<CPinyinDlg>,
	public CWinDataExchange<CPinyinDlg>
{
public:
	enum { IDD = IDD_DLG_PINYIN };

	BEGIN_MSG_MAP(CPinyinDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
		COMMAND_ID_HANDLER(IDOK, OnClickOk)
		COMMAND_ID_HANDLER(IDCANCEL, OnCloseCmd)
	END_MSG_MAP()

	BEGIN_DDX_MAP(CPinyinDlg)
		DDX_TEXT(IDC_EDIT_WORD, m_word)
		DDX_TEXT(IDC_EDIT_AB, m_ab)
	END_DDX_MAP();

	CString m_word;
	CString m_ab;

	// Handler prototypes (uncomment arguments if needed):
	//	LRESULT MessageHandler(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& /*bHandled*/)
	//	LRESULT CommandHandler(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
	//	LRESULT NotifyHandler(int /*idCtrl*/, LPNMHDR /*pnmh*/, BOOL& /*bHandled*/)

	LRESULT OnInitDialog(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& /*bHandled*/);
	LRESULT OnCloseCmd(WORD /*wNotifyCode*/, WORD wID, HWND /*hWndCtl*/, BOOL& /*bHandled*/);

	//»ñÈ¡ºº×ÖÆ´ÒôÊ××ÖÄ¸
	LRESULT GetChineseSpell(CString strText, CString& strPY);


	LRESULT OnClickOk(WORD /*wNotifyCode*/, WORD wID, HWND /*hWndCtl*/, BOOL& /*bHandled*/);
};
